import './style.css';
import {defaultSuppliers,decimal,cents,money,quantity,normalize,today,candidates,validateState,equivalentProduct,aggregateEquivalentItems,productSimilarity,synonymStats} from './core.js';
import {parseQuotation,pdfText} from './import.js';
const uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>String(n).replace('.',',');
const price=n=>(n/100).toFixed(2).replace('.',',');
const initial=()=>({version:1,title:'Compra '+new Date().toLocaleDateString('pt-BR'),suppliers:structuredClone(defaultSuppliers),items:[],offers:[],productAliases:[],ignoredEquivalences:[],buyer:{name:'Pharmapenha',cnpj:'',address:'',contact:'',notes:''}});
let state=initial(),view='home',plan=null,approved=false,worker=null,draft=null,local=false;
let pdfQueue=[],pdfIndex=0,pdfGeneration=0;
async function nextPDF(){
 const generation=++pdfGeneration;
 if(pdfIndex>=pdfQueue.length){pdfQueue=[];draft=null;render();notice('Fila concluída. As cotações confirmadas foram adicionadas.');return}
 const file=pdfQueue[pdfIndex];draft=null;
 modal('Lendo PDF',`<p role="status">Arquivo ${pdfIndex+1} de ${pdfQueue.length}: ${esc(file.name)}</p><p>Extraindo texto. Aguarde…</p>`);
 try{const text=await pdfText(file);if(generation!==pdfGeneration)return;showDraft(text)}catch(err){if(generation!==pdfGeneration)return;formError(err.message)}
 if(generation!==pdfGeneration)return;
 document.querySelector('#modal-body').insertAdjacentHTML('afterbegin',`<p class="storage">Arquivo ${pdfIndex+1} de ${pdfQueue.length} · ${esc(file.name)}</p>`);
 document.querySelector('#modal-body').insertAdjacentHTML('beforeend',`<div class="actions">${btn('Pular este arquivo','skip-pdf')}</div>`);
}
function closeImport(){if(pdfQueue.length&&!confirm('Encerrar a importação dos arquivos restantes? As cotações já confirmadas serão mantidas.'))return;pdfGeneration++;pdfQueue=[];draft=null;document.querySelector('#modal').close()}
try{if(localStorage.getItem('pharma-local-consent')==='yes'){const saved=localStorage.getItem('pharma-round');if(saved)state=validateState(JSON.parse(saved));local=true}}catch{}
const root=document.querySelector('#app');
const supplier=id=>state.suppliers.find(s=>s.id===id);
function persist(){if(local)try{localStorage.setItem('pharma-round',JSON.stringify(state))}catch{notice('Não foi possível salvar neste aparelho. Salve a cotação em arquivo para não perder os dados.')}}
function changed(){worker?.terminate();worker=null;plan=null;approved=false;persist();render()}
function notice(msg){const el=document.querySelector('#notice');el.textContent=msg;el.hidden=false;el.scrollIntoView({block:'nearest'})}
function input(name,label,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function select(name,label,values,current){return `<label>${esc(label)}<select name="${name}">${values.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`}
const units=(cur)=>select('unit','Unidade',[['g','g'],['kg','kg'],['ml','ml'],['l','L'],['un','unidade'],['mlh','MLH (mil unidades)']],cur||'g');
const btn=(text,action,id='',cls='')=>`<button type="button" class="${cls}" data-act="${action}" data-id="${esc(id)}">${text}</button>`;
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function render(){
 const workspace=['items','offers','plan'].includes(view);
 const tabs=[['offers','1. Adicionar cotações'],['items','2. Conferir itens'],['plan','3. Pedidos e PDFs']];
 root.innerHTML=`<header><div><strong>Pharmapenha · Compras</strong><span>Comparar, organizar e fechar pedidos</span></div>${view!=='home'?`<div class="actions">${btn('Início','tab','home')}${hasQuote()?btn('Salvar cotação em arquivo','backup'):''}</div>`:''}</header>${workspace?`<nav aria-label="Etapas da cotação">${tabs.map(([v,t])=>`<button data-act="tab" data-id="${v}" aria-current="${view===v?'page':'false'}" class="${view===v?'active':''}">${t}</button>`).join('')}</nav>`:''}<main>${workspace?`<div class="bar"><h1>${esc(state.title)}</h1>${btn('Renomear','rename')}</div><p class="storage">${local?'Salvamento neste aparelho ativado. Não sincroniza com outros computadores.':'Dados desta sessão: salve a cotação em arquivo antes de fechar ou recarregar a página.'} <button data-act="tab" data-id="data">Configurar</button></p>`:''}<p id="notice" role="status" class="notice" hidden></p>${({home:homeView,items:itemsView,offers:offersView,plan:planView,suppliers:suppliersView,data:dataView}[view])()}${workspace?`<div class="actions secondary-tools">${btn('Fornecedores e mínimos','tab','suppliers')}${btn('Dados e backup','tab','data')}</div>`:view!=='home'&&hasQuote()?btn('Voltar à cotação','tab','offers'):''}</main><dialog id="modal"><div id="modal-body"></div></dialog><input type="file" id="restore-file" accept=".json" hidden><input type="file" id="pdf-file" accept="application/pdf,.pdf" multiple hidden>`;
}
function hasQuote(){return Boolean(state.started||state.items.length||state.offers.length)}
function homeView(){return `<div class="home"><section><h1>Suas cotações</h1><p>Comece uma compra ou abra uma cotação salva em arquivo.</p><div class="actions home-actions">${btn('+ Nova cotação','new-round','','primary')}${btn('Abrir cotação salva','restore')}</div></section>${hasQuote()?`<section><small>Cotação em andamento</small><h2>${esc(state.title)}</h2><p>${state.items.length} itens · ${state.offers.length} ofertas de fornecedores</p><div class="actions">${btn('Continuar cotação','tab','offers','primary')}${btn('Salvar em arquivo','backup')}</div><p class="hint">${local?'Salva neste aparelho. Guarde também uma cópia em arquivo.':'Disponível nesta sessão. Salve em arquivo antes de fechar a página.'}</p></section>`:''}<details><summary>Configurações</summary><div class="actions secondary-tools">${btn('Fornecedores e mínimos','tab','suppliers')}${btn('Dados e backup','tab','data')}</div></details></div>`}
function newQuote(){modal('Nova cotação',`<form id="new-quote-form" class="form-grid">${input('title','Nome da cotação','Cotação '+new Date().toLocaleDateString('pt-BR'),'text','required maxlength="120"')}${hasQuote()?`<div class="full warning">Ao criar, a cotação atual será substituída. Para guardá-la, feche esta janela e salve em arquivo primeiro.</div><label class="check full"><input type="checkbox" name="replace" required> Já salvei o que preciso e quero iniciar outra cotação.</label>`:''}<p class="hint full">Fornecedores, mínimos e dados da Pharmapenha serão mantidos.</p><div class="actions full"><button class="primary" type="submit">Criar cotação</button>${btn('Cancelar','close')}</div></form>`)}
function itemsView(){
 const rows=state.items.map(i=>{const opts=candidates(i,state.offers,state.suppliers);return `<tr><td><strong>${esc(i.name)}</strong><small>${i.enabled===false?'Fora desta compra':esc(i.unit)}</small></td><td>${i.qty} ${esc(i.unit)}${i.allowExcess?'<small>Arredondar embalagem permitido</small>':''}</td><td>${opts.length?`${opts.length} opções válidas`:'Sem oferta válida'}</td><td>${i.lock?esc(supplier(i.lock)?.name):'Automático'}</td><td class="actions">${btn('Editar','item',i.id)}${btn('Excluir','remove-item',i.id,'danger')}</td></tr>`});
 const aliases=state.productAliases||[];
 const ignored=state.ignoredEquivalences||[],pairKey=(x,y)=>[normalize(x.name),normalize(y.name)].sort().join('|');
 const possible=[];for(let a=0;a<state.items.length;a++)for(let b=a+1;b<state.items.length;b++){const x=state.items[a],y=state.items[b],score=x.unit===y.unit?productSimilarity(x.name,y.name,aliases):0;if(score>=.5&&score<1&&!ignored.includes(pairKey(x,y)))possible.push({x,y,score})}
 return `<section><div class="section-head"><div><h2>Lista de compra</h2><p>Informe a quantidade necessária. Nomes equivalentes ficam reunidos no mesmo produto.</p></div><div class="actions">${btn('Agrupar equivalentes','aggregate')}${btn('+ Adicionar item','item','','primary')}</div></div>${rows.length?table(['Produto / especificação','Quantidade necessária','Cotações disponíveis','Fornecedor fixado','Ações'],rows):'<div class="empty">Adicione os produtos manualmente ou importe um PDF na etapa 1.</div>'}<p class="hint">A compra de cada item será feita em um único fornecedor. kg vira g, L vira ml e MLH vira unidades. Massa, volume e unidades nunca são misturados.</p>${possible.length?`<details open><summary>Possíveis equivalências para revisar (${possible.length})</summary><p class="hint">O sistema não uniu estes nomes sozinho. Confirme somente quando forem o mesmo insumo-base.</p>${table(['Produto','Possível equivalente','Semelhança','Decisão'],possible.map(p=>`<tr><td>${esc(p.x.name)}</td><td>${esc(p.y.name)}</td><td>${Math.round(p.score*100)}%</td><td class="actions">${btn('Unificar','merge-items',`${p.x.id}|${p.y.id}`)}${btn('Manter separados','ignore-pair',`${p.x.id}|${p.y.id}`)}</td></tr>`))}</details>`:''}<details><summary>Base de sinônimos e aprendizado</summary><p>${synonymStats.materials.toLocaleString('pt-BR')} matérias-primas · ${synonymStats.names.toLocaleString('pt-BR')} nomes reconhecidos · ${synonymStats.ambiguous} nomes ambíguos protegidos contra associação automática.</p>${aliases.length?table(['Nome recebido','Comparar como',''],aliases.map((a,i)=>`<tr><td>${esc(a.alias)}</td><td>${esc(a.canonical)}</td><td>${btn('Remover','remove-alias',String(i),'danger')}</td></tr>`)):'<p class="hint">Nenhuma equivalência adicional aprendida nesta cotação.</p>'}<div class="actions">${btn('Baixar mapa para revisão','review-report')}</div></details><div class="actions">${btn('Montar pedidos →','calculate','','primary')}</div></section>`;
}
function offersView(){
 const rows=state.offers.map(o=>{const i=state.items.find(x=>x.id===o.productId);const unit=o.grossCents/o.packQty;return `<tr><td>${esc(i?.name)}<small>${esc(o.description)}</small></td><td>${esc(supplier(o.supplierId)?.name)}<small>${esc(o.reference)}</small></td><td>${o.packQty} ${o.unit}</td><td>${money(o.grossCents)}<small>Sem impostos: ${money(o.netCents)}</small></td><td>${(unit/100).toLocaleString('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:6})} R$/${o.unit}</td><td>${o.available===false?'Indisponível':o.reviewed?'Conferida':'Não conferida'}<small>${o.expires?esc(o.expires):'Prazo não informado'}</small></td><td class="actions">${btn('Editar','offer',o.id)}${btn('Excluir','remove-offer',o.id,'danger')}</td></tr>`});
 return `<section><div class="section-head"><div><h2>Cotações recebidas</h2><p>PDF com texto, mensagem copiada ou lançamento manual. Confira os valores antes de usar.</p></div><div class="actions">${btn('Importar PDFs','pdf','','primary')}${btn('Colar mensagem','paste')}${btn('+ Oferta manual','offer')}</div></div>${rows.length?table(['Produto','Fornecedor','Embalagem','Preço da embalagem','Preço normalizado','Situação','Ações'],rows):'<div class="empty">Nenhuma cotação adicionada. Seus PDFs não são enviados para um servidor.</div>'}<p class="hint">Preço final inclui os impostos informados. O mínimo considera produtos sem impostos por padrão, sem frete; você pode alterar a base em Fornecedores. PDFs digitalizados precisam de entrada manual nesta versão.</p><div class="actions">${btn('Conferir itens →','tab','items','primary')}</div></section>`;
}
function planView(){
 let content='';
 if(worker)content='<p role="status">Calculando combinações e verificando os mínimos…</p>';
 else if(!plan)content='<div class="empty">Depois de conferir quantidades e cotações, clique em Calcular pedidos.</div>';
 else if(plan.status!=='feasible'){
  const messages={empty:'Adicione pelo menos um item à compra.',missing:'Itens sem opção válida: '+plan.missing.join(', ')+'. Confira disponibilidade, quantidade da embalagem e fornecedor fixado. A data da cotação não bloqueia o cálculo.',infeasible:'Não existe distribuição válida dentro das opções cadastradas e da regra de um fornecedor por item. Não foram aumentadas quantidades para completar mínimos.',inconclusive:'A busca atingiu o limite sem encontrar uma distribuição válida. Isso não prova que ela seja impossível; reduza as opções ou fixe fornecedores e tente novamente.'};
  content=`<p class="warning">${esc(messages[plan.status])}</p>${plan.baselineOrders?`<h3>Distribuição pelos menores preços, ainda não válida</h3>${table(['Fornecedor','Base do mínimo','Mínimo','Falta'],plan.baselineOrders.map(o=>`<tr><td>${esc(o.supplier.name)}</td><td>${money(o.basis)}</td><td>${money(o.supplier.minCents)}</td><td>${money(o.shortfall)}</td></tr>`))}`:''}<p>Os PDFs ficam bloqueados enquanto não houver uma distribuição válida.</p>`;
 }else{
  content=`<div class="summary"><div><small>Total com fretes informados</small><strong>${money(plan.total)}</strong></div><div><small>Produtos nos menores preços, sem mínimos e sem frete</small><strong>${money(plan.baselineTotal)}</strong></div><div><small>Pedidos válidos</small><strong>${plan.orders.length}</strong></div></div><p class="${plan.optimal?'notice':'warning'}">${plan.optimal?'Menor custo encontrado com busca completa, dentro das ofertas, quantidades e regras cadastradas.':'Distribuição válida encontrada; a busca atingiu o limite. Não há garantia de menor custo.'}</p>${plan.orders.some(o=>!o.supplier.freightKnown)?'<p class="warning">Há fretes não confirmados. São tratados como zero no cálculo, mas não são considerados grátis. Confirme-os em Fornecedores antes de decidir.</p>':''}<p class="hint">Não desconta ou consolida fornecedores com nomes diferentes. Infinity Pharma e Fagron têm cadastros separados. Ofertas devem representar produtos tecnicamente equivalentes.</p>`;
  if(plan.changes.length)content+=`<details open><summary>Por que alguns itens mudaram de fornecedor?</summary>${table(['Produto','Menor preço inicial','Fornecedor escolhido','Diferença nos produtos'],plan.changes.map(c=>`<tr><td>${esc(c.product)}</td><td>${esc(c.from)}</td><td>${esc(c.to)}</td><td>${money(c.difference)}</td></tr>`))}<p class="hint">Redistribuições para atender os mínimos e reduzir o custo total, incluindo fretes informados.</p></details>`;
  content+=plan.orders.map(o=>`<article class="order"><div class="section-head"><h3>${esc(o.supplier.name)}</h3><strong>${money(o.total)}</strong></div><p>Mínimo ${money(o.supplier.minCents)} · base atingida ${money(o.basis)} · frete ${o.supplier.freightKnown?money(o.supplier.freightCents):'a confirmar'}</p>${table(['Item','Embalagens','Quantidade total','Valor final'],o.lines.map(l=>`<tr><td>${esc(l.product)}${l.excess?`<small class="warning-text">${l.excess} ${l.unit} extras autorizados</small>`:''}</td><td>${l.packs} × ${l.packQty} ${l.unit}</td><td>${l.qty} ${l.unit}</td><td>${money(l.gross)}</td></tr>`))}<div class="actions"><button data-act="pdf-order" data-id="${o.supplier.id}" ${!approved?'disabled':''}>Baixar pedido em PDF</button></div></article>`).join('');
  content+=`<div class="review"><label class="check"><input type="checkbox" id="approve" ${approved?'checked':''}> Revisei produtos, quantidades, preços, mínimos e condições de frete. Autorizo gerar os arquivos destes pedidos.</label><div class="actions"><button class="primary" data-act="all-pdf" ${!approved?'disabled':''}>Baixar todos os PDFs (ZIP)</button>${btn('Dados da Pharmapenha no pedido','buyer')}</div><p class="hint">Os arquivos não são enviados automaticamente. Cada fornecedor recebe apenas os itens e os preços do seu próprio pedido.</p></div>`;
 }
 return `<section><div class="section-head"><div><h2>Pedidos separados por fornecedor</h2><p>Primeiro calcula, depois você confere e baixa os PDFs.</p></div>${btn(worker?'Calculando…':'Calcular pedidos','calculate','','primary')}</div>${content}</section>`;
}
function suppliersView(){return `<section><div class="section-head"><div><h2>Fornecedores e pedidos mínimos</h2><p>${state.suppliers.length} fornecedores cadastrados. Frete não entra no mínimo.</p></div>${btn('+ Fornecedor','supplier')}</div>${table(['Fornecedor','Pedido mínimo','Base do mínimo','Frete por pedido',''],state.suppliers.map(s=>`<tr><td>${esc(s.name)}</td><td>${money(s.minCents)}</td><td>${s.minimumBasis==='gross'?'Com impostos':'Sem impostos'}</td><td>${s.freightKnown?money(s.freightCents):'Não confirmado'}</td><td>${btn('Editar','supplier',s.id)}</td></tr>`))}</section>`}
function dataView(){return `<section><h2>Dados e continuidade da compra</h2><p>Esta versão não tem banco de dados compartilhado nem login da equipe. O conteúdo das cotações é processado no seu navegador e não entra no GitHub.</p><label class="check"><input id="local-save" type="checkbox" ${local?'checked':''}> Salvar automaticamente neste aparelho (não usar em computador compartilhado)</label><p class="hint">Limpar os dados do navegador pode apagar essa cópia. Baixe o arquivo da cotação para guardar e abrir em outro computador. O arquivo contém preços e informações comerciais; guarde-o em local seguro. Os PDFs originais não são incluídos.</p><div class="actions">${btn('Salvar cotação em arquivo','backup','','primary')}${btn('Abrir cotação salva','restore')}${btn('Dados da Pharmapenha','buyer')}${btn('Nova cotação','new-round','','danger')}</div></section>`}
function modal(title,html){const d=document.querySelector('#modal');document.querySelector('#modal-body').innerHTML=`<div class="section-head"><h2>${esc(title)}</h2>${btn('Fechar','close')}</div>${html}<p id="modal-error" class="warning" role="alert" hidden></p>`;d.showModal()}
function formError(msg){const e=document.querySelector('#modal-error');if(e){e.hidden=false;e.textContent=msg}else notice(msg)}
function form(title,id,html){modal(title,`<form id="${id}" class="form-grid">${html}<div class="actions full"><button type="submit" class="primary">Salvar e voltar</button></div></form>`)}
function itemForm(id){const i=state.items.find(x=>x.id===id)||{};form('Item da compra','item-form',`<input name="id" type="hidden" value="${esc(id)}">${input('name','Produto e especificação',i.name,'text','required maxlength="200"')}${input('qty','Quantidade necessária',i.qty??'','text','required inputmode="decimal"')}${units(i.unit)}${select('lock','Escolha do fornecedor',[['','Automática'],...state.suppliers.map(s=>[s.id,s.name])],i.lock||'')}<label class="check full"><input name="allowExcess" type="checkbox" ${i.allowExcess?'checked':''}> Permitir arredondar a quantidade para a próxima embalagem inteira (o excedente aparecerá no pedido)</label><label class="check full"><input name="enabled" type="checkbox" ${i.enabled===false?'':'checked'}> Incluir nesta compra</label>`)}
function offerForm(id){if(!state.items.length){itemForm('');document.querySelector('#modal-body h2').textContent='Primeiro, cadastre o produto da oferta';return}const o=state.offers.find(x=>x.id===id)||{};form('Oferta do fornecedor','offer-form',`<input name="id" type="hidden" value="${esc(id)}">${select('productId','Vincular ao produto (mesma especificação)',state.items.map(i=>[i.id,i.name]),o.productId||state.items[0].id)}${select('supplierId','Fornecedor',state.suppliers.map(s=>[s.id,s.name]),o.supplierId||state.suppliers[0].id)}${input('description','Descrição usada pelo fornecedor',o.description)}${input('packQty','Quantidade por embalagem',o.packQty,'text','required inputmode="decimal"')}${units(o.unit)}${input('net','Preço da embalagem sem impostos (R$)',o.netCents!=null?price(o.netCents):'','text','required inputmode="decimal"')}${input('gross','Preço final da embalagem com impostos (R$)',o.grossCents!=null?price(o.grossCents):'','text','required inputmode="decimal"')}${input('maxPacks','Máximo de embalagens disponível (vazio = não informado)',o.maxPacks??'','number','min="0" step="1"')}${input('reference','Número/referência da cotação',o.reference)}${input('expires','Data limite informada (não bloqueia)',o.expires,'date')}${input('validity','Validade do produto',o.validity)}<label class="check"><input type="checkbox" name="available" ${o.available===false?'':'checked'}> Disponível</label><label class="check full"><input name="reviewed" type="checkbox" required ${o.reviewed?'checked':''}> Conferi descrição, equivalência, unidade, preço por embalagem, impostos.</label>`)}
function supplierForm(id){const s=supplier(id)||{};form('Condições do fornecedor','supplier-form',`<input name="id" type="hidden" value="${esc(id)}">${input('name','Nome',s.name,'text','required')}${input('min','Pedido mínimo (R$)',price(s.minCents??0),'text','required inputmode="decimal"')}${select('minimumBasis','O mínimo é calculado sobre',[['net','Produtos sem impostos e sem frete'],['gross','Produtos com impostos, sem frete']],s.minimumBasis||'net')}${input('freight','Frete fixo por pedido (R$)',price(s.freightCents??0),'text','required inputmode="decimal"')}<label class="check full"><input name="freightKnown" type="checkbox" ${s.freightKnown?'checked':''}> Frete confirmado (marque também quando for grátis)</label><p class="hint full">Frete variável, descontos por faixa e condições de pagamento devem ser confirmados antes de enviar o pedido.</p>`)}
function buyerForm(){const b=state.buyer||{};form('Identificação no pedido PDF','buyer-form',`${input('name','Razão social / nome',b.name,'text','required maxlength="180"')}${input('cnpj','CNPJ',b.cnpj)}${input('address','Endereço de entrega',b.address,'text','maxlength="350"')}${input('contact','Contato',b.contact)}<label class="full">Observações para todos os pedidos<textarea name="notes" maxlength="3000">${esc(b.notes)}</textarea></label>`)}
function showDraft(text){draft=parseQuotation(text);if(!draft.rows.length){formError('Nenhum item reconhecido. Use “Oferta manual” ou uma linha por item: Produto 500 g — R$ 98,00.');if(!document.querySelector('#modal').open)modal('Não foi possível extrair os itens',`<p>Use a entrada manual para este formato. Nenhum item foi importado.</p><details><summary>Texto extraído</summary><pre>${esc(text)}</pre></details>`);return}
 const chosen=state.suppliers.find(s=>normalize(s.name)===normalize(draft.detected))?.id||'';
 modal('Conferir antes de importar',`<form id="draft-form"><div class="form-grid">${select('supplierId','Fornecedor',[['','Selecione'],...state.suppliers.map(s=>[s.id,s.name])],chosen)}${input('reference','Referência da cotação',draft.reference)}${input('expires','Data limite informada (não bloqueia)',draft.expires,'date')}</div><p class="warning">Em “Comparar como”, confirme o produto equivalente. Teor, porcentagem, “extrato seco” e hidratação são ignorados no agrupamento; sais e formas químicas diferentes continuam separados. Quando você corrigir uma associação, o sistema aprende o nome.</p>${table(['Importar / comparar como','Descrição original','Embalagem','Unidade','Sem impostos R$','Final R$','Disponível'],draft.rows.map((r,i)=>{const match=state.items.find(p=>p.unit===r.unit&&equivalentProduct(p.name,r.description,state.productAliases));return `<tr><td><label class="check"><input name="use-${i}" type="checkbox" checked> Incluir</label><select name="match-${i}"><option value="">Criar item separado</option>${state.items.filter(p=>p.unit===r.unit).map(p=>`<option value="${p.id}" ${p.id===match?.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></td><td><input aria-label="Descrição ${i+1}" name="description-${i}" value="${esc(r.description)}" required></td><td><input aria-label="Embalagem ${i+1}" name="qty-${i}" value="${num(r.qty)}" required inputmode="decimal"></td><td><select name="unit-${i}" aria-label="Unidade ${i+1}">${['g','ml','un'].map(u=>`<option ${r.unit===u?'selected':''}>${u}</option>`).join('')}</select></td><td><input aria-label="Preço sem impostos ${i+1}" name="net-${i}" value="${price(r.net)}" required inputmode="decimal"></td><td><input aria-label="Preço final ${i+1}" name="gross-${i}" value="${price(r.gross)}" required inputmode="decimal"></td><td><input aria-label="Disponível ${i+1}" name="available-${i}" type="checkbox" ${r.available?'checked':''}></td></tr>`}))}<details><summary>Conferir texto completo e linhas não reconhecidas (${draft.unparsed.length})</summary><p>Cabeçalhos, rodapés e itens não reconhecidos estão aqui. Cadastre manualmente qualquer produto faltante.</p><pre>${esc(text)}</pre></details><label class="check"><input type="checkbox" required> Conferi a cotação original, unidades, preços, equivalências e eventuais itens não extraídos.</label><button class="primary" type="submit">Confirmar importação</button></form>`);
}
async function calculate(){if(worker)return;state=aggregateEquivalentItems(state);persist();view='plan';approved=false;plan=null;worker=new Worker(new URL('./optimizer.worker.js',import.meta.url),{type:'module'});render();worker.onmessage=e=>{worker.terminate();worker=null;if(e.data.error){notice(e.data.error);return}plan=e.data.result;render()};worker.onerror=()=>{worker?.terminate();worker=null;render();notice('Falha no cálculo. Seus dados foram mantidos. Tente novamente.')};worker.postMessage({items:state.items,offers:state.offers,suppliers:state.suppliers})}
async function action(act,id){
 if(act==='tab'){view=id;render()}
 if(act==='close')closeImport();
 if(act==='skip-pdf'){pdfIndex++;await nextPDF()}
 if(act==='item')itemForm(id);
 if(act==='offer')offerForm(id);
 if(act==='supplier')supplierForm(id);
 if(act==='buyer')buyerForm();
 if(act==='rename')form('Nome da cotação','rename-form',input('title','Nome',state.title,'text','required maxlength="120"'));
 if(act==='remove-item'&&confirm('Excluir este item e todas as ofertas vinculadas? Baixe um backup para manter uma cópia.')){state.items=state.items.filter(i=>i.id!==id);state.offers=state.offers.filter(o=>o.productId!==id);changed()}
 if(act==='remove-offer'&&confirm('Excluir esta oferta?')){state.offers=state.offers.filter(o=>o.id!==id);changed()}
 if(act==='aggregate'){const before=state.items.length;state=aggregateEquivalentItems(state);changed();notice(before===state.items.length?'Nenhum item equivalente novo foi encontrado.':`${before-state.items.length} item(ns) equivalente(s) foram reunidos.`)}
 if(act==='remove-alias'){state.productAliases.splice(Number(id),1);changed()}
 if(act==='merge-items'){
  const [targetId,sourceId]=id.split('|'),target=state.items.find(i=>i.id===targetId),source=state.items.find(i=>i.id===sourceId);if(!target||!source)return;
  if(confirm(`Unificar “${source.name}” com “${target.name}”? As ofertas serão comparadas juntas.`)){state.productAliases.push({alias:source.name,canonical:target.name});target.qty=Math.max(target.qty,source.qty);target.allowExcess=Boolean(target.allowExcess||source.allowExcess);for(const o of state.offers)if(o.productId===source.id)o.productId=target.id;state.items=state.items.filter(i=>i.id!==source.id);changed()}
 }
 if(act==='ignore-pair'){const [a,b]=id.split('|').map(x=>state.items.find(i=>i.id===x));if(a&&b){state.ignoredEquivalences??=[];state.ignoredEquivalences.push([normalize(a.name),normalize(b.name)].sort().join('|'));changed()}}
 if(act==='new-round')newQuote();
 if(act==='pdf')document.querySelector('#pdf-file').click();
 if(act==='paste')modal('Colar cotação recebida',`<form id="paste-form"><label>Uma linha por item<textarea name="text" required rows="10" placeholder="Magnésio quelato 500 g — R$ 98,00"></textarea></label><p>Preço por embalagem. Revise impostos e descrições na próxima tela.</p><button class="primary">Interpretar e revisar</button></form>`);
 if(act==='calculate')await calculate();
 if(act==='restore')document.querySelector('#restore-file').click();
 if(act==='backup'){const {download,slug}=await import('./pdf.js');download(JSON.stringify(state,null,2),`${slug(state.title)}.json`,'application/json')}
 if(act==='review-report'){const {download,slug}=await import('./pdf.js');const groups=state.items.map(i=>({produto:i.name,unidade:i.unit,nomesRecebidos:[...new Set(state.offers.filter(o=>o.productId===i.id).map(o=>o.description))],fornecedores:[...new Set(state.offers.filter(o=>o.productId===i.id).map(o=>supplier(o.supplierId)?.name).filter(Boolean))]}));download(JSON.stringify({cotacao:state.title,geradoEm:new Date().toISOString(),base:synonymStats,grupos:groups,equivalenciasAprendidas:state.productAliases,decisoesManterSeparado:state.ignoredEquivalences},null,2),`Mapa-equivalencias-${slug(state.title)}.json`,'application/json')}
 if(['pdf-order','all-pdf'].includes(act)){if(!approved||plan?.status!=='feasible')throw Error('Calcule e revise o pedido antes de gerar PDFs.');const {download,orderPDF,allPDFs,slug}=await import('./pdf.js');if(act==='pdf-order'){const o=plan.orders.find(o=>o.supplier.id===id);download(orderPDF(o,state.buyer,state.title),`Pedido-${slug(o.supplier.name)}.pdf`)}else download(allPDFs(plan.orders,state.buyer,state.title),`Pedidos-${slug(state.title)}.zip`,'application/zip')}
}
root.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b)action(b.dataset.act,b.dataset.id).catch(err=>formError(err.message))});
root.addEventListener('change',async e=>{
 if(e.target.id==='approve'){approved=e.target.checked;render()}
 if(e.target.id==='local-save'){local=e.target.checked;try{localStorage.setItem('pharma-local-consent',local?'yes':'no');if(!local)localStorage.removeItem('pharma-round')}catch{}persist();render()}
 if(e.target.id==='pdf-file'){
  const files=Array.from(e.target.files);e.target.value='';if(!files.length)return;
  pdfQueue=files;pdfIndex=0;await nextPDF();
 }
 if(e.target.id==='restore-file'){
  const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Arquivo maior que 10 MB.');const s=validateState(JSON.parse(await file.text()));if(!hasQuote()||confirm('Abrir esta cotação e substituir a atual? Salve a atual em arquivo antes.')){state={...s,started:true};view='offers';changed()}}catch(err){notice(err.message)}
 }
});
root.addEventListener('submit',e=>{e.preventDefault();const f=e.target;const d=new FormData(f);const get=n=>String(d.get(n)||'');const checked=n=>d.has(n);try{
 if(f.getAttribute('id')==='paste-form'){showDraft(get('text'));return}
 if(f.getAttribute('id')==='new-quote-form'){const title=get('title').trim();if(!title)throw Error('Informe o nome da cotação.');if(hasQuote()&&!checked('replace'))throw Error('Confirme a substituição da cotação atual.');state={...state,started:true,title,items:[],offers:[]};view='offers'}
 if(f.getAttribute('id')==='rename-form')state.title=get('title').trim();
 if(f.getAttribute('id')==='buyer-form')state.buyer=Object.fromEntries(d);
 if(f.getAttribute('id')==='item-form'){
  const q=quantity(decimal(get('qty')),get('unit'));const item={id:get('id')||uid(),name:get('name').trim(),...q,lock:get('lock'),allowExcess:checked('allowExcess'),enabled:checked('enabled')};if(!item.name)throw Error('Informe o produto.');const old=state.items.findIndex(i=>i.id===item.id);if(old>=0)state.items[old]=item;else state.items.push(item);
 }
 if(f.getAttribute('id')==='offer-form'){
  const q=quantity(decimal(get('packQty')),get('unit')),net=cents(get('net')),gross=cents(get('gross'));if(!Number.isSafeInteger(net)||net<=0||!Number.isSafeInteger(gross)||gross<net)throw Error('Confira os preços: o final não pode ser menor que o valor sem impostos.');
  const item=state.items.find(i=>i.id===get('productId'));if(item.unit!==q.unit)throw Error('Unidade incompatível com o produto escolhido.');
  const max=get('maxPacks')===''?null:Number(get('maxPacks'));if(max!==null&&(!Number.isInteger(max)||max<0))throw Error('Máximo disponível deve ser inteiro e não negativo.');
  const o={id:get('id')||uid(),productId:item.id,supplierId:get('supplierId'),description:get('description').trim()||item.name,packQty:q.qty,unit:q.unit,netCents:net,grossCents:gross,maxPacks:max,reference:get('reference'),expires:get('expires'),validity:get('validity'),available:checked('available'),reviewed:checked('reviewed')};const old=state.offers.findIndex(x=>x.id===o.id);if(old>=0)state.offers[old]=o;else state.offers.push(o);
 }
 if(f.getAttribute('id')==='supplier-form'){
  const min=cents(get('min')),freight=cents(get('freight'));if(!Number.isSafeInteger(min)||min<0||!Number.isSafeInteger(freight)||freight<0)throw Error('Mínimo e frete devem ser valores não negativos.');
  const s={id:get('id')||uid(),name:get('name').trim(),minCents:min,freightCents:freight,freightKnown:checked('freightKnown'),minimumBasis:get('minimumBasis')};if(!s.name)throw Error('Informe o nome.');if(state.suppliers.some(x=>x.id!==s.id&&normalize(x.name)===normalize(s.name)))throw Error('Esse fornecedor já está cadastrado.');const old=state.suppliers.findIndex(x=>x.id===s.id);if(old>=0)state.suppliers[old]=s;else state.suppliers.push(s);
 }
 if(f.getAttribute('id')==='draft-form'){
  if(!get('supplierId'))throw Error('Selecione o fornecedor.');const next=structuredClone(state);let count=0;
  draft.rows.forEach((r,i)=>{if(!checked(`use-${i}`))return;const q=quantity(decimal(get(`qty-${i}`)),get(`unit-${i}`)),net=cents(get(`net-${i}`)),gross=cents(get(`gross-${i}`)),description=get(`description-${i}`).trim();if(!description||!Number.isSafeInteger(net)||net<0||!Number.isSafeInteger(gross)||gross<net)throw Error(`Confira valores da linha ${i+1}.`);if(checked(`available-${i}`)&&net===0)throw Error('Oferta disponível deve ter preço positivo.');let item=next.items.find(x=>x.id===get(`match-${i}`));if(item&&item.unit!==q.unit)throw Error(`Unidade incompatível na linha ${i+1}.`);if(item&&normalize(description)!==normalize(item.name)&&!next.productAliases.some(a=>normalize(a.alias)===normalize(description)&&normalize(a.canonical)===normalize(item.name)))next.productAliases.push({alias:description,canonical:item.name});if(!item){item={id:uid(),name:description,qty:q.qty*Math.max(1,r.quotedPacks||1),unit:q.unit,enabled:true,allowExcess:false,lock:''};next.items.push(item)}
   const o={id:uid(),productId:item.id,supplierId:get('supplierId'),description,packQty:q.qty,unit:q.unit,netCents:net,grossCents:gross,reference:get('reference'),expires:get('expires'),validity:r.validity||'',available:checked(`available-${i}`),reviewed:true,maxPacks:null};
   const old=next.offers.findIndex(x=>x.productId===o.productId&&x.supplierId===o.supplierId&&x.packQty===o.packQty&&x.reference===o.reference);if(old>=0)next.offers[old]=o;else next.offers.push(o);count++;
  });if(!count)throw Error('Selecione pelo menos uma linha.');state=aggregateEquivalentItems(validateState(next));draft=null;
 }
 document.querySelector('#modal').close();changed();
 if(f.getAttribute('id')==='draft-form'&&pdfQueue.length){pdfIndex++;nextPDF().catch(err=>formError(err.message))}
 if(f.getAttribute('id')==='item-form'&&view==='offers')offerForm('');
}catch(err){formError(err.message)}});
window.addEventListener('beforeunload',e=>{if(!local&&(state.items.length||state.offers.length)){e.preventDefault();e.returnValue=''}});
root.addEventListener('cancel',e=>{if(e.target.id==='modal'){e.preventDefault();closeImport()}},true);
render();
