import './style.css';
import {defaultSuppliers,decimal,cents,money,quantity,normalize,today,candidates,ordersFor,lowestSelections,choiceHighlights,validateState,equivalentProduct,aggregateEquivalentItems,productSimilarity,equivalentGroups,synonymStats} from './core.js';
import {parseQuotation,quotationText} from './import.js';
import {cloudConfigured,getCloudUser,signIn,signOut,listCloudRounds,saveCloudRound,deleteCloudRound,uploadQuotationFile,listProductAliases,saveProductAlias,deleteProductAlias} from './cloud.js';
const uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>String(n).replace('.',',');
const price=n=>(n/100).toFixed(2).replace('.',',');
const initial=()=>({version:1,title:'Compra '+new Date().toLocaleDateString('pt-BR'),suppliers:structuredClone(defaultSuppliers),items:[],offers:[],productAliases:[],ignoredEquivalences:[],buyer:{name:'Pharmapenha',cnpj:'',address:'',contact:'',notes:''}});
let state=initial(),view='home',plan=null,approved=false,worker=null,draft=null,local=false;
let cloudReady=!cloudConfigured,cloudUser=null,cloudRounds=[],cloudRoundId=null,cloudTimer=null,cloudSavePromise=null,planMode='compare',globalAliases=[];
let pdfQueue=[],pdfIndex=0,pdfGeneration=0;
async function nextPDF(){
 const generation=++pdfGeneration;
 if(pdfIndex>=pdfQueue.length){pdfQueue=[];draft=null;render();notice('Fila concluída. As cotações confirmadas foram adicionadas.');return}
 const file=pdfQueue[pdfIndex];draft=null;
 modal('Lendo cotação',`<p role="status">Arquivo ${pdfIndex+1} de ${pdfQueue.length}: ${esc(file.name)}</p><p id="read-progress">Extraindo texto. Fotos e documentos escaneados podem demorar um pouco…</p>`);
 if(cloudUser){try{await saveCurrentCloud();if(cloudRoundId)await uploadQuotationFile(cloudRoundId,file)}catch(err){notice('O arquivo será analisado, mas não foi guardado na nuvem: '+err.message)}}
 try{const text=await quotationText(file,p=>{const el=document.querySelector('#read-progress');if(el)el.textContent=`Reconhecendo imagem${p.page?` · página ${p.page} de ${p.pages}`:''}${Number.isFinite(p.percent)?` · ${p.percent}%`:''}…`});if(generation!==pdfGeneration)return;showDraft(text)}catch(err){if(generation!==pdfGeneration)return;formError(err.message)}
 if(generation!==pdfGeneration)return;
 document.querySelector('#modal-body').insertAdjacentHTML('afterbegin',`<p class="storage">Arquivo ${pdfIndex+1} de ${pdfQueue.length} · ${esc(file.name)}</p>`);
 document.querySelector('#modal-body').insertAdjacentHTML('beforeend',`<div class="actions">${btn('Pular este arquivo','skip-pdf')}</div>`);
}
function closeImport(){if(pdfQueue.length&&!confirm('Encerrar a importação dos arquivos restantes? As cotações já confirmadas serão mantidas.'))return;pdfGeneration++;pdfQueue=[];draft=null;document.querySelector('#modal').close()}
try{if(localStorage.getItem('pharma-local-consent')==='yes'){const saved=localStorage.getItem('pharma-round');if(saved)state=validateState(JSON.parse(saved));local=true}}catch{}
const root=document.querySelector('#app');
const supplier=id=>state.suppliers.find(s=>s.id===id);
function persist(){
 if(local)try{localStorage.setItem('pharma-round',JSON.stringify(state))}catch{notice('Não foi possível salvar neste aparelho. Salve a cotação em arquivo para não perder os dados.')}
 if(cloudUser&&hasQuote()){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>saveCurrentCloud().catch(err=>notice('Falha ao salvar na nuvem: '+err.message)),700)}
}
function mergeKnownAliases(target){target.productAliases=target.productAliases||[];for(const a of globalAliases)if(!target.productAliases.some(x=>normalize(x.alias)===normalize(a.alias)))target.productAliases.push(a);return target}
async function rememberAlias(alias,canonical){if(normalize(alias)===normalize(canonical))return;const local={alias,canonical};if(!state.productAliases.some(a=>normalize(a.alias)===normalize(alias)))state.productAliases.push(local);if(!cloudUser)return;const saved=await saveProductAlias(alias,canonical,normalize(alias),normalize(canonical));globalAliases=globalAliases.filter(a=>normalize(a.alias)!==normalize(alias));globalAliases.unshift(saved)}
async function refreshCloudRounds(){cloudRounds=await listCloudRounds();for(const row of cloudRounds)mergeKnownAliases(row.state)}
async function saveCurrentCloud(){if(!cloudUser||!hasQuote())return null;if(cloudSavePromise)return cloudSavePromise;cloudSavePromise=(async()=>{const row=await saveCloudRound(cloudRoundId,state);cloudRoundId=row.id;const old=cloudRounds.findIndex(x=>x.id===row.id);if(old>=0)cloudRounds[old]=row;else cloudRounds.unshift(row);return row})();try{return await cloudSavePromise}finally{cloudSavePromise=null}}
async function bootCloud(){
 if(!cloudConfigured){render();return}
 try{cloudUser=await getCloudUser();if(cloudUser){globalAliases=await listProductAliases();mergeKnownAliases(state);await refreshCloudRounds()}}catch(err){console.error(err)}
 cloudReady=true;render();
 if(cloudUser&&hasQuote()&&!cloudRoundId)persist();
}
function changed(){worker?.terminate();worker=null;plan=null;approved=false;persist();render()}
function notice(msg){const el=document.querySelector('#notice');if(el){el.textContent=msg;el.hidden=false}}
function input(name,label,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function select(name,label,values,current){return `<label>${esc(label)}<select name="${name}">${values.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`}
const units=(cur)=>select('unit','Unidade',[['g','g'],['kg','kg'],['ml','ml'],['l','L'],['un','unidade'],['mlh','MLH (mil unidades)']],cur||'g');
const btn=(text,action,id='',cls='')=>`<button type="button" class="${cls}" data-act="${action}" data-id="${esc(id)}">${text}</button>`;
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function render(){
 if(cloudConfigured&&!cloudReady){root.innerHTML='<main class="auth-shell"><section class="auth-card loading-card"><img class="brand-logo login-logo" src="/pharmapenha-logo.png" alt="Pharmapenha"><h1>Pharmapenha · Compras</h1><p>Conectando ao sistema…</p></section></main>';return}
 if(cloudConfigured&&!cloudUser){root.innerHTML=loginView();return}
 const workspace=['items','offers','plan'].includes(view);
 const tabs=[['offers','1','Cotações'],['items','2','Produtos'],['plan','3','Comparar e fechar']];
 const userName=cloudUser?.email?.split('@')[0]||'';
 root.innerHTML=`<header class="app-header"><div class="header-inner"><div class="brand"><img class="brand-logo" src="/pharmapenha-logo.png" alt="Pharmapenha"><div><strong>Pharmapenha</strong><span>Central de compras</span></div></div><div class="header-tools">${cloudUser?`<span class="cloud-pill"><i></i> Nuvem conectada</span><span class="user-pill">${esc(userName)}</span>`:''}${view!=='home'?btn('Início','tab','home'):''}</div></div></header>${workspace?`<nav class="steps" aria-label="Etapas da cotação"><div class="steps-inner">${tabs.map(([v,n,t])=>`<button data-act="tab" data-id="${v}" aria-current="${view===v?'step':'false'}" class="step ${view===v?'active':''}"><span>${n}</span>${t}</button>`).join('')}</div></nav>`:''}<main>${workspace?`<div class="workspace-head"><div><span class="eyebrow">Cotação em andamento</span><h1>${esc(state.title)}</h1></div><div class="actions">${btn('Renomear','rename')}${btn('Backup','backup')}</div></div><div class="save-strip"><span><i></i>${cloudUser?'Salva automaticamente na nuvem':'Salvamento somente neste aparelho'}</span><button data-act="tab" data-id="data">Configurações</button></div>`:''}<p id="notice" role="status" class="notice toast" hidden></p>${({home:homeView,items:itemsView,offers:offersView,plan:planView,suppliers:suppliersView,data:dataView}[view])()}${workspace?`<div class="actions secondary-tools">${btn('Fornecedores e mínimos','tab','suppliers')}${btn('Dados e backup','tab','data')}</div>`:view!=='home'&&hasQuote()?btn('Voltar à cotação','tab','offers'):''}</main><dialog id="modal"><div id="modal-body"></div></dialog><input type="file" id="restore-file" accept=".json" hidden><input type="file" id="pdf-file" accept="application/pdf,.pdf,image/jpeg,image/png,image/webp,image/bmp,image/tiff,text/html,.html,.htm,text/plain,.txt" multiple hidden>`;
}
function renderInPlace(target){const y=window.scrollY,top=target?.getBoundingClientRect().top,cls=['order-choice','order-packs','order-payment','order-freight'].find(c=>target?.classList.contains(c)),key=target?.dataset.offer||target?.dataset.id;render();requestAnimationFrame(()=>{const same=cls?[...document.querySelectorAll(`.${cls}`)].find(x=>(x.dataset.offer||x.dataset.id)===key):null;if(same&&Number.isFinite(top))window.scrollBy(0,same.getBoundingClientRect().top-top);else window.scrollTo(0,y)})}
function hasQuote(){return Boolean(state.started||state.items.length||state.offers.length)}
function loginView(){return `<main class="auth-shell"><section class="auth-card"><img class="brand-logo login-logo" src="/pharmapenha-logo.png" alt="Pharmapenha"><span class="eyebrow">Sistema interno</span><h1>Pharmapenha · Compras</h1><p>Acesse as cotações salvas da equipe.</p><form id="login-form" class="form-grid"><label class="full">E-mail<input name="email" type="email" autocomplete="username" placeholder="seuemail@pharmapenha.com.br" required></label><label class="full">Senha<input name="password" type="password" autocomplete="current-password" required></label><button class="primary full">Entrar no sistema</button></form><p id="login-error" class="warning" role="alert" hidden></p></section></main>`}
function cloudStatus(status){return ({draft:'Em andamento',review:'Aguardando revisão',ordered:'Pedido realizado',closed:'Finalizada'})[status]||'Em andamento'}
function homeView(){
 const active=cloudRounds.filter(r=>r.status!=='closed').length;
 const rounds=cloudConfigured?cloudRounds.map(r=>`<article class="cloud-round"><div class="round-icon">${esc((r.title||'C').charAt(0).toUpperCase())}</div><div class="round-main"><span class="status-chip ${r.status}">${esc(cloudStatus(r.status))}</span><h2>${esc(r.title)}</h2><p>${r.state?.items?.length||0} produtos · ${r.state?.offers?.length||0} ofertas</p><small>Atualizada ${new Date(r.updated_at).toLocaleString('pt-BR')}</small></div><div class="round-actions">${btn('Abrir cotação','cloud-open',r.id,'primary')}${btn('Excluir','cloud-delete',r.id,'icon-danger')}</div></article>`).join(''):'';
 return `<div class="home dashboard"><section class="welcome-card"><div><span class="eyebrow">Compras Pharmapenha</span><h1>Suas cotações</h1><p>Crie uma rodada ou continue exatamente de onde a equipe parou.</p></div><div class="actions home-actions">${btn('+ Nova cotação','new-round','','primary')}${btn('Importar backup','restore')}</div></section>${cloudConfigured?`<div class="dashboard-stats"><div><span>Cotações salvas</span><strong>${cloudRounds.length}</strong></div><div><span>Em andamento</span><strong>${active}</strong></div><div><span>Armazenamento</span><strong class="online"><i></i> Online</strong></div></div><section class="rounds-section"><div class="section-head"><div><h2>Cotações da equipe</h2><p>As alterações são salvas automaticamente.</p></div>${btn('Sair','cloud-logout')}</div>${rounds?`<div class="cloud-rounds">${rounds}</div>`:'<div class="empty"><strong>Nenhuma cotação salva ainda</strong><span>Crie a primeira cotação para começar.</span></div>'}</section>`:hasQuote()?`<section><h2>${esc(state.title)}</h2><p>${state.items.length} produtos · ${state.offers.length} ofertas</p><div class="actions">${btn('Continuar cotação','tab','offers','primary')}${btn('Salvar em arquivo','backup')}</div></section>`:''}<details class="settings-box"><summary>Configurações do sistema</summary><div class="actions secondary-tools">${btn('Fornecedores e mínimos','tab','suppliers')}${btn('Dados e backup','tab','data')}</div></details></div>`;
}
function newQuote(){modal('Nova cotação',`<form id="new-quote-form" class="form-grid">${input('title','Nome da cotação','Cotação '+new Date().toLocaleDateString('pt-BR'),'text','required maxlength="120"')}${hasQuote()?`<div class="full warning">Ao criar, a cotação atual será substituída. Para guardá-la, feche esta janela e salve em arquivo primeiro.</div><label class="check full"><input type="checkbox" name="replace" required> Já salvei o que preciso e quero iniciar outra cotação.</label>`:''}<p class="hint full">Fornecedores, mínimos e dados da Pharmapenha serão mantidos.</p><div class="actions full"><button class="primary" type="submit">Criar cotação</button>${btn('Cancelar','close')}</div></form>`)}
function itemsView(){
 const aliases=state.productAliases||[];
 const ignored=state.ignoredEquivalences||[],possible=equivalentGroups(state.items,state.offers,aliases,ignored);
 const productCard=i=>{const opts=candidates(i,state.offers,state.suppliers),raw=state.offers.filter(o=>o.productId===i.id).map(o=>o.description||i.name),names=[...new Set(raw.filter(n=>normalize(n)!==normalize(i.name)))];return `<article class="product-review-card"><div class="product-review-main"><span class="eyebrow">Matéria-prima unificada</span><h3>${esc(i.name)}</h3><div class="alias-chips">${names.length?names.map(n=>`<span class="alias-chip">${esc(n)}</span>`).join(''):'<span class="alias-chip neutral">Mesmo nome em todas as cotações</span>'}</div></div><div class="product-review-meta"><strong>${i.qty} ${esc(i.unit)}</strong><span>${opts.length} ${opts.length===1?'oferta válida':'ofertas válidas'}</span>${i.lock?`<small>Fixado: ${esc(supplier(i.lock)?.name)}</small>`:''}</div><div class="card-actions">${btn('Editar','item',i.id)}${btn('Excluir','remove-item',i.id,'danger')}</div></article>`};
 const available=state.items.filter(i=>candidates(i,state.offers,state.suppliers).length),missing=state.items.filter(i=>!candidates(i,state.offers,state.suppliers).length);
 return `<section><div class="section-head"><div><span class="eyebrow">Etapa 2</span><h2>Conferência por matéria-prima</h2><p>Cada produto aparece uma única vez. Abaixo dele ficam os diferentes nomes recebidos.</p></div><div class="actions">${btn('Agrupar equivalentes','aggregate')}${btn('+ Adicionar item','item','','primary')}</div></div>${state.items.length?`<div class="overview-strip"><div><strong>${state.items.length}</strong><span>produtos unificados</span></div><div><strong>${state.offers.length}</strong><span>ofertas recebidas</span></div><div class="${missing.length?'attention':''}"><strong>${missing.length}</strong><span>sem oferta válida</span></div></div>${missing.length?`<section class="no-offers-panel"><div class="section-head"><div><span class="eyebrow">Conferir de uma vez</span><h3>Sem oferta disponível (${missing.length})</h3><p>Todos os itens que precisam de atenção estão reunidos aqui.</p></div></div><div class="missing-products">${missing.map(i=>`<div><span><strong>${esc(i.name)}</strong><small>${i.qty} ${esc(i.unit)}</small></span><span class="card-actions">${btn('Editar','item',i.id)}${btn('Excluir','remove-item',i.id,'danger')}</span></div>`).join('')}</div></section>`:''}<div class="products-review">${available.map(productCard).join('')}</div>`:'<div class="empty">Adicione os produtos manualmente ou importe uma cotação na etapa 1.</div>'}<p class="hint">kg vira g, L vira ml e MLH vira unidades. Massa, volume e unidades nunca são misturados.</p>${possible.length?`<p class="notice">Há ${possible.length} sugestão${possible.length===1?'':'ões'} de equivalência aguardando decisão na etapa 1.</p>`:''}<details><summary>Base de equivalências e aprendizado</summary><p>${synonymStats.materials.toLocaleString('pt-BR')} matérias-primas · ${synonymStats.names.toLocaleString('pt-BR')} nomes reconhecidos · ${synonymStats.ambiguous} nomes ambíguos protegidos.</p>${aliases.length?table(['Nome recebido','Comparar como',''],aliases.map((a,i)=>`<tr><td>${esc(a.alias)}</td><td>${esc(a.canonical)}</td><td>${btn('Remover','remove-alias',String(i),'danger')}</td></tr>`)):'<p class="hint">Nenhuma equivalência adicional aprendida nesta cotação.</p>'}<div class="actions">${btn('Baixar mapa para revisão','review-report')}</div></details><div class="sticky-action"><div><strong>${available.length} produtos prontos para comparar</strong><span>${missing.length?`${missing.length} ainda precisam de conferência`:'Todos os produtos têm oferta válida'}</span></div>${btn('Comparar fornecedores →','calculate','','primary')}</div></section>`;
}
function offersView(){
 const groups=state.suppliers.map(s=>({s,offers:state.offers.filter(o=>o.supplierId===s.id)})).filter(g=>g.offers.length),needsReview=state.offers.filter(o=>!o.reviewed).length;
 const suggestions=groups.length>=2?equivalentGroups(state.items,state.offers,state.productAliases||[],state.ignoredEquivalences||[]):[];
 const suggestionPanel=suggestions.length?`<section class="equivalence-suggestions"><div class="section-head"><div><span class="eyebrow">Conferência inteligente</span><h3>Sugestões de produtos equivalentes</h3><p>O sistema encontrou nomes possivelmente usados para a mesma matéria-prima. Confirme antes de comparar preços.</p></div><span class="suggestion-count">${suggestions.length}</span></div><div class="equivalence-grid">${suggestions.map(group=>{const all=[group.primary,...group.alternatives],ids=all.map(i=>i.id).join('|');return `<article class="equivalence-card"><div class="canonical-choice"><span>Nome principal sugerido</span><strong>${esc(group.primary.name)}</strong></div><div class="equivalent-names">${all.map(item=>{const names=[...new Set(state.offers.filter(o=>o.productId===item.id).map(o=>supplier(o.supplierId)?.name).filter(Boolean))];return `<div class="equivalent-name ${item.id===group.primary.id?'principal':''}"><span>${item.id===group.primary.id?'Manter como principal':'Possível equivalente'}</span><strong>${esc(item.name)}</strong><small>${names.join(' · ')}</small></div>`}).join('')}</div><div class="equivalence-actions">${btn('✓ Unificar produtos','merge-group',ids,'primary')}${btn('Manter separados','ignore-group',ids)}</div></article>`}).join('')}</div></section>`:'';
 const cards=groups.map(({s,offers})=>{const valid=offers.filter(o=>o.reviewed&&o.available!==false&&o.considered!==false).length,refs=[...new Set(offers.map(o=>o.reference).filter(Boolean))];return `<details class="supplier-quote-card"><summary><div><span class="supplier-avatar">${esc(s.name.charAt(0))}</span><span><strong>${esc(s.name)}</strong><small>${refs.length?refs.map(esc).join(' · '):'Sem número de referência'}</small></span></div><div class="supplier-quote-totals"><strong>${valid}/${offers.length}</strong><span>ofertas válidas</span></div><span class="expand-label">Ver itens</span></summary><div class="offer-list">${offers.map(o=>{const i=state.items.find(x=>x.id===o.productId),unit=o.grossCents/o.packQty,status=o.available===false?'Indisponível':o.considered===false?'Desconsiderada':o.reviewed?'Conferida':'Conferir';return `<article class="offer-row"><div class="offer-product"><strong>${esc(i?.name||'Produto não vinculado')}</strong>${normalize(o.description)!==normalize(i?.name)?`<small>Recebido como: ${esc(o.description)}</small>`:''}</div><div><span>Embalagem</span><strong>${o.packQty} ${esc(o.unit)}</strong></div><div><span>Preço final</span><strong>${money(o.grossCents)}</strong><small>${(unit/100).toLocaleString('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:6})} R$/${esc(o.unit)}</small></div><span class="status-chip ${status==='Conferida'?'ordered':status==='Conferir'?'review':'draft'}">${status}</span><div class="card-actions">${btn('Editar','offer',o.id)}${btn('Excluir','remove-offer',o.id,'danger')}</div></article>`}).join('')}</div></details>`}).join('');
 return `<section><div class="section-head"><div><span class="eyebrow">Etapa 1</span><h2>Cotações por fornecedor</h2><p>Uma linha por fornecedor. Abra somente quando precisar conferir os itens.</p></div><div class="actions">${btn('Importar arquivos','pdf','','primary')}${btn('Colar mensagem','paste')}${btn('+ Oferta manual','offer')}</div></div>${groups.length?`<div class="overview-strip"><div><strong>${groups.length}</strong><span>fornecedores</span></div><div><strong>${state.offers.length}</strong><span>ofertas recebidas</span></div><div class="${needsReview?'attention':''}"><strong>${needsReview}</strong><span>para conferir</span></div></div>${suggestionPanel}<div class="supplier-quotes">${cards}</div>`:'<div class="empty">Nenhuma cotação adicionada. Importe PDFs, fotos, HTMLs ou mensagens.</div>'}<p class="hint">A partir da segunda cotação, possíveis equivalências aparecem acima para decisão do comprador.</p><div class="sticky-action"><div><strong>${groups.length} fornecedores adicionados</strong><span>${suggestions.length?`${suggestions.length} equivalência${suggestions.length===1?' aguarda':'s aguardam'} confirmação`:needsReview?`${needsReview} ofertas ainda precisam ser conferidas`:'Cotações prontas para organizar'}</span></div>${btn('Organizar por produto →','tab','items','primary')}</div></section>`;
}
function planView(){
 let content='';
 if(worker)content='<div class="empty loading-state"><strong>Calculando as melhores opções…</strong><span>Comparando preços, embalagens e pedidos mínimos.</span></div>';
 else if(!plan)content='<div class="empty"><strong>Comparação ainda não calculada</strong><span>Depois de conferir os produtos, clique em Calcular comparação.</span></div>';
 else if(plan.status!=='feasible'){
  const messages={empty:'Adicione pelo menos um produto à compra.',missing:'Produtos sem opção válida: '+plan.missing.join(', ')+'. Confira disponibilidade, embalagem e fornecedor fixado.',infeasible:'Não existe distribuição válida com as opções cadastradas.',inconclusive:'A busca atingiu o limite. Reduza as opções ou fixe fornecedores e tente novamente.'};
  content=`<p class="warning">${esc(messages[plan.status])}</p>`;
 }else{
  const selectedCount=Object.keys(plan.selections||{}).length;
  content=`<div class="summary"><div><span>Total atual</span><strong>${money(plan.total)}</strong><small>Com fretes informados</small></div><div><span>Produtos selecionados</span><strong>${selectedCount}</strong><small>de ${state.items.filter(i=>i.enabled!==false).length}</small></div><div><span>Fornecedores</span><strong>${plan.orders.length}</strong><small>com pedido</small></div></div><div class="mode-switch"><button data-act="plan-mode" data-id="compare" class="${planMode==='compare'?'active':''}">Comparar por produto</button><button data-act="plan-mode" data-id="orders" class="${planMode==='orders'?'active':''}">Pedidos por fornecedor</button></div>`;
  if(planMode==='compare'){
   const itemCards=state.items.filter(i=>i.enabled!==false).map(item=>{
    const choices=(plan.choices||[]).filter(c=>c.itemId===item.id);
    if(!choices.length)return `<article class="product-compare missing-card"><div class="product-title"><div><span class="eyebrow">Sem oferta válida</span><h3>${esc(item.name)}</h3></div><strong>${item.qty} ${esc(item.unit)}</strong></div></article>`;
    const options=choices.sort((a,b)=>a.gross-b.gross).map(c=>{const h=plan.highlights?.[c.offerId]||{},chosen=plan.selections?.[c.itemId]===c.offerId;return `<article class="quote-option ${chosen?'chosen':''}">${chosen?'<div class="chosen-ribbon">✓ Escolhido</div>':''}<label class="option-select"><input class="order-choice" type="checkbox" data-item="${esc(c.itemId)}" data-offer="${esc(c.offerId)}" ${chosen?'checked':''}><span>${chosen?'Trocar':'Escolher'}</span></label><div class="option-head"><strong>${esc(supplier(c.supplierId)?.name)}</strong><div class="badges">${h.lowestUnit?`<span class="badge unit-best">Menor R$/${c.unit}</span>`:''}${h.lowestOutlay?'<span class="badge outlay-best">Menor desembolso</span>':''}</div></div><small>${esc(c.description)}${c.reference?` · ${esc(c.reference)}`:''}</small><div class="option-metrics"><div><span>Preço proporcional</span><strong>${(c.pricePerUnit/100).toLocaleString('pt-BR',{minimumFractionDigits:4,maximumFractionDigits:6})} R$/${c.unit}</strong></div><div><span>Embalagem</span><strong>${c.packQty} ${c.unit}</strong></div><div><span>Valor final</span><strong>${money(c.gross)}</strong></div></div><div class="pack-editor"><label>Embalagens<input class="order-packs" type="number" min="1" step="1" value="${c.packs}" data-offer="${esc(c.offerId)}"></label><span>Total ${c.qty} ${c.unit}${c.excess?` · sobra ${c.excess} ${c.unit}`:''}</span></div>${h.savingsAgainstUnitBest?`<p class="tradeoff">O ${c.unit} custa ${num(h.unitPremiumPercent)}% mais, mas esta compra fica ${money(h.savingsAgainstUnitBest)} mais barata.</p>`:''}</article>`}).join('');
    return `<section class="product-compare"><div class="product-title"><div><span class="eyebrow">Necessidade: ${item.qty} ${esc(item.unit)}</span><h3>${esc(item.name)}</h3></div><span class="option-count">${choices.length} ${choices.length===1?'oferta':'ofertas'}</span></div><div class="quote-options">${options}</div></section>`;
   }).join('');
   content+=`<div class="explain-card"><div><strong>Escolha pelo que realmente importa</strong><p>Azul indica o melhor preço proporcional. Verde indica o menor valor que sai do caixa considerando as embalagens.</p></div></div><div class="product-comparisons">${itemCards}</div><div class="sticky-action"><div><strong>${selectedCount} produtos selecionados</strong><span>${money(plan.total)} no total atual</span></div><button class="primary" data-act="plan-mode" data-id="orders">Revisar pedidos →</button></div>`;
  }else{
   if(plan.orders.some(o=>!o.freightKnown))content+='<p class="warning">Há fretes a confirmar. Eles estão zerados no total, mas não são considerados grátis.</p>';
   if(plan.unassigned?.length)content+=`<p class="warning"><strong>${plan.unassigned.length} produto${plan.unassigned.length===1?'':'s'} sem fornecedor:</strong> ${plan.unassigned.map(i=>esc(i.name)).join(', ')}.</p>`;
   if(plan.suggestionStatus==='feasible'&&plan.changes.length)content+=`<details><summary>Sugestão opcional para atingir pedidos mínimos</summary><p class="hint">O sistema não altera suas escolhas. Estas transferências são apenas uma sugestão.</p>${table(['Produto','Escolha atual','Possível transferência','Diferença'],plan.changes.map(c=>`<tr><td>${esc(c.product)}</td><td>${esc(c.from)}</td><td>${esc(c.to)}</td><td>${money(c.difference)}</td></tr>`))}</details>`;
   const exclusions=state.offers.filter(o=>o.considered===false).length;if(exclusions)content+=`<p class="notice"><strong>${exclusions} oferta${exclusions===1?'':'s'} desconsiderada${exclusions===1?'':'s'}.</strong> Os motivos aparecerão somente no relatório interno do Luiz.</p>`;
   const choiceCards=state.suppliers.flatMap(s=>{const choices=plan.choices?.filter(c=>c.supplierId===s.id)||[];if(!choices.length)return[];const o=plan.orders.find(x=>x.supplier.id===s.id),settings=plan.orderSettings?.[s.id]||{};return [`<article class="supplier-order ${o?'selected-order':'empty-order'}"><div class="supplier-order-head"><div><span class="status-chip ${o?'ordered':'draft'}">${o?'Pedido ativo':'Sem itens'}</span><h3>${esc(s.name)}</h3><p>${o?`${o.lines.length} item${o.lines.length===1?'':'s'} selecionado${o.lines.length===1?'':'s'}`:'Nenhum PDF será gerado'}</p></div><strong>${o?money(o.total):money(0)}</strong></div>${o&&!o.meetsMinimum?`<p class="minimum-alert">Faltam ${money(o.shortfall)} para o pedido mínimo. O PDF continua liberado.</p>`:''}<div class="supplier-lines">${choices.map(c=>{const chosen=plan.selections?.[c.itemId]===c.offerId;return `<div class="supplier-line ${chosen?'chosen':''}"><label class="check compact"><input class="order-choice" type="checkbox" data-item="${esc(c.itemId)}" data-offer="${esc(c.offerId)}" ${chosen?'checked':''}></label><div><strong>${esc(c.product)}</strong><small>${esc(c.description)}</small></div><div class="line-packs"><input class="order-packs" type="number" min="1" step="1" value="${c.packs}" data-offer="${esc(c.offerId)}" aria-label="Embalagens de ${esc(c.product)}"><small>× ${c.packQty} ${c.unit}</small></div><strong>${money(c.gross)}</strong></div>`}).join('')}</div><div class="order-conditions"><label>Pagamento<input class="order-payment" data-id="${s.id}" value="${esc(settings.payment||'')}" placeholder="Ex.: boleto 28 dias"></label><label>Frete (R$)<input class="order-freight" data-id="${s.id}" value="${settings.freightKnown?price(settings.freightCents):''}" inputmode="decimal" placeholder="A confirmar"></label></div><div class="supplier-footer">${btn('+ Item manual','manual-order-item',s.id)}${o?`<button data-act="pdf-order" data-id="${s.id}" ${!approved?'disabled':''}>Baixar PDF</button>`:''}</div></article>`]});
   content+=`<div class="supplier-orders">${choiceCards.join('')}</div><div class="review"><label class="check"><input type="checkbox" id="approve" ${approved?'checked':''}> Revisei produtos, quantidades, preços, pagamento e frete.</label><div class="actions"><button class="primary" data-act="all-pdf" ${!approved?'disabled':''}>Baixar todos os pedidos</button><button data-act="internal-report">Relatório interno do Luiz</button>${btn('Dados da Pharmapenha','buyer')}</div></div>`;
  }
 }
 return `<section class="plan-shell"><div class="section-head"><div><span class="eyebrow">Etapa 3</span><h2>Comparação e fechamento</h2><p>Decida por produto e depois confira os pedidos separados.</p></div>${btn(worker?'Calculando…':'Calcular comparação','calculate','','primary')}</div>${content}</section>`;
}
function suppliersView(){return `<section><div class="section-head"><div><h2>Fornecedores e pedidos mínimos</h2><p>${state.suppliers.length} fornecedores cadastrados. Frete não entra no mínimo.</p></div>${btn('+ Fornecedor','supplier')}</div>${table(['Fornecedor','Pedido mínimo','Base do mínimo','Frete por pedido',''],state.suppliers.map(s=>`<tr><td>${esc(s.name)}</td><td>${money(s.minCents)}</td><td>${s.minimumBasis==='gross'?'Com impostos':'Sem impostos'}</td><td>${s.freightKnown?money(s.freightCents):'Não confirmado'}</td><td>${btn('Editar','supplier',s.id)}</td></tr>`))}</section>`}
function dataView(){return `<section><h2>Dados e continuidade da compra</h2><p>Esta versão não tem banco de dados compartilhado nem login da equipe. O conteúdo das cotações é processado no seu navegador e não entra no GitHub.</p><label class="check"><input id="local-save" type="checkbox" ${local?'checked':''}> Salvar automaticamente neste aparelho (não usar em computador compartilhado)</label><p class="hint">Limpar os dados do navegador pode apagar essa cópia. Baixe o arquivo da cotação para guardar e abrir em outro computador. O arquivo contém preços e informações comerciais; guarde-o em local seguro. Os PDFs originais não são incluídos.</p><div class="actions">${btn('Salvar cotação em arquivo','backup','','primary')}${btn('Abrir cotação salva','restore')}${btn('Dados da Pharmapenha','buyer')}${btn('Nova cotação','new-round','','danger')}</div></section>`}
function modal(title,html){const d=document.querySelector('#modal');document.querySelector('#modal-body').innerHTML=`<div class="section-head"><h2>${esc(title)}</h2>${btn('Fechar','close')}</div>${html}<p id="modal-error" class="warning" role="alert" hidden></p>`;d.showModal()}
function formError(msg){const e=document.querySelector('#modal-error')||document.querySelector('#login-error');if(e){e.hidden=false;e.textContent=msg}else notice(msg)}
function form(title,id,html){modal(title,`<form id="${id}" class="form-grid">${html}<div class="actions full"><button type="submit" class="primary">Salvar e voltar</button></div></form>`)}
function itemForm(id){const i=state.items.find(x=>x.id===id)||{};form('Item da compra','item-form',`<input name="id" type="hidden" value="${esc(id)}">${input('name','Produto e especificação',i.name,'text','required maxlength="200"')}${input('qty','Quantidade necessária',i.qty??'','text','required inputmode="decimal"')}${units(i.unit)}${select('lock','Escolha do fornecedor',[['','Automática'],...state.suppliers.map(s=>[s.id,s.name])],i.lock||'')}<label class="check full"><input name="allowExcess" type="checkbox" ${i.allowExcess?'checked':''}> Permitir arredondar a quantidade para a próxima embalagem inteira (o excedente aparecerá no pedido)</label><label class="check full"><input name="enabled" type="checkbox" ${i.enabled===false?'':'checked'}> Incluir nesta compra</label>`)}
function offerForm(id){if(!state.items.length){itemForm('');document.querySelector('#modal-body h2').textContent='Primeiro, cadastre o produto da oferta';return}const o=state.offers.find(x=>x.id===id)||{},considered=o.considered!==false;form('Oferta do fornecedor','offer-form',`<input name="id" type="hidden" value="${esc(id)}">${select('productId','Vincular ao produto (mesma especificação)',state.items.map(i=>[i.id,i.name]),o.productId||state.items[0].id)}${select('supplierId','Fornecedor',state.suppliers.map(s=>[s.id,s.name]),o.supplierId||state.suppliers[0].id)}${input('description','Descrição usada pelo fornecedor',o.description)}${input('packQty','Quantidade por embalagem',o.packQty,'text','required inputmode="decimal"')}${units(o.unit)}${input('net','Preço da embalagem sem impostos (R$)',o.netCents!=null?price(o.netCents):'','text','required inputmode="decimal"')}${input('gross','Preço final da embalagem com impostos (R$)',o.grossCents!=null?price(o.grossCents):'','text','required inputmode="decimal"')}${input('maxPacks','Máximo de embalagens disponível (vazio = não informado)',o.maxPacks??'','number','min="0" step="1"')}${input('reference','Número/referência da cotação',o.reference)}${input('expires','Data limite informada (não bloqueia)',o.expires,'date')}${input('validity','Validade do produto',o.validity)}<label class="check"><input type="checkbox" name="available" ${o.available===false?'':'checked'}> Disponível no fornecedor</label><label class="check full"><input id="considered" type="checkbox" name="considered" ${considered?'checked':''}> Considerar esta oferta na comparação</label><label id="exclusion-reason-field" class="full" ${considered?'hidden':''}>Motivo para desconsiderar (mínimo 10 caracteres)<textarea name="exclusionReason" minlength="10" maxlength="500" ${considered?'':'required'}>${esc(o.exclusionReason||'')}</textarea></label><label class="check full"><input name="reviewed" type="checkbox" required ${o.reviewed?'checked':''}> Conferi descrição, equivalência, unidade, preço por embalagem e impostos.</label>`)}
function supplierForm(id){const s=supplier(id)||{};form('Condições do fornecedor','supplier-form',`<input name="id" type="hidden" value="${esc(id)}">${input('name','Nome',s.name,'text','required')}${input('min','Pedido mínimo (R$)',price(s.minCents??0),'text','required inputmode="decimal"')}${select('minimumBasis','O mínimo é calculado sobre',[['net','Produtos sem impostos e sem frete'],['gross','Produtos com impostos, sem frete']],s.minimumBasis||'net')}${input('freight','Frete fixo por pedido (R$)',price(s.freightCents??0),'text','required inputmode="decimal"')}<label class="check full"><input name="freightKnown" type="checkbox" ${s.freightKnown?'checked':''}> Frete confirmado (marque também quando for grátis)</label><p class="hint full">Frete variável, descontos por faixa e condições de pagamento devem ser confirmados antes de enviar o pedido.</p>`)}
function buyerForm(){const b=state.buyer||{};form('Identificação no pedido PDF','buyer-form',`${input('name','Razão social / nome',b.name,'text','required maxlength="180"')}${input('cnpj','CNPJ',b.cnpj)}${input('address','Endereço de entrega',b.address,'text','maxlength="350"')}${input('contact','Contato',b.contact)}<label class="full">Observações para todos os pedidos<textarea name="notes" maxlength="3000">${esc(b.notes)}</textarea></label>`)}
function recalculateOrder(o){
 o.net=o.lines.reduce((t,l)=>t+l.net,0);o.gross=o.lines.reduce((t,l)=>t+l.gross,0);o.tax=o.gross-o.net;o.basis=o.supplier.minimumBasis==='gross'?o.gross:o.net;o.shortfall=Math.max(0,o.supplier.minCents-o.basis);o.meetsMinimum=o.shortfall===0;o.valid=o.lines.length>0;o.total=o.gross+(o.freightKnown?o.freightCents:0);return o;
}
function manualOrderItemForm(id){const s=supplier(id);if(!s||plan?.status!=='feasible')return;form(`Incluir item no pedido · ${s.name}`,'manual-order-item-form',`<input type="hidden" name="supplierId" value="${esc(id)}">${input('product','Produto / descrição','','text','required maxlength="250"')}${input('packs','Número de embalagens','1','number','required min="1" step="1"')}${input('packQty','Quantidade por embalagem','','text','required inputmode="decimal"')}${units('g')}${input('net','Preço por embalagem sem impostos (R$)','','text','required inputmode="decimal"')}${input('gross','Preço final por embalagem (R$)','','text','required inputmode="decimal"')}${input('reference','Referência / observação','','text','maxlength="250"')}<p class="hint full">O item será marcado automaticamente neste fornecedor e entrará nos totais, no PDF do pedido e no relatório consolidado do Luiz.</p>`)}
function rebuildPlan(){
 if(plan?.status!=='feasible')return;plan.highlights=choiceHighlights(plan.choices);const lines=(plan.choices||[]).filter(c=>plan.selections?.[c.itemId]===c.offerId);plan.orders=ordersFor(lines,state.suppliers,true).map(o=>{const settings=plan.orderSettings[o.supplier.id];return recalculateOrder({...o,payment:settings.payment,freightKnown:settings.freightKnown,freightCents:settings.freightCents})});plan.lines=lines;plan.total=plan.orders.reduce((t,o)=>t+o.total,0);plan.baselineTotal=plan.orders.reduce((t,o)=>t+o.gross,0);plan.unassigned=state.items.filter(i=>i.enabled!==false&&!plan.selections?.[i.id]);
}
function showDraft(text,forcedSupplier=''){draft=parseQuotation(text);if(!draft.rows.length){formError('Nenhum item reconhecido. Use o modelo completo de copiar e colar ou cadastre uma oferta manual.');if(!document.querySelector('#modal').open)modal('Não foi possível extrair os itens',`<p>Use a entrada manual para este formato. Nenhum item foi importado.</p><details><summary>Texto extraído</summary><pre>${esc(text)}</pre></details>`);return}
 const chosen=forcedSupplier||state.suppliers.find(s=>normalize(s.name)===normalize(draft.detected))?.id||'';
 modal('Conferir antes de importar',`<form id="draft-form"><div class="form-grid">${select('supplierId','Fornecedor',[['','Selecione'],...state.suppliers.map(s=>[s.id,s.name])],chosen)}${input('reference','Referência da cotação',draft.reference)}${input('expires','Data limite informada (não bloqueia)',draft.expires,'date')}</div><p class="warning">Em “Comparar como”, confirme o produto equivalente. Teor, porcentagem, “extrato seco” e hidratação são ignorados no agrupamento; sais e formas químicas diferentes continuam separados. Quando você corrigir uma associação, o sistema aprende o nome.</p>${table(['Importar / comparar como','Descrição original','Embalagem','Unidade','Sem impostos R$','Final R$','Disponível'],draft.rows.map((r,i)=>{const match=state.items.find(p=>p.unit===r.unit&&equivalentProduct(p.name,r.description,state.productAliases));return `<tr><td><label class="check"><input name="use-${i}" type="checkbox" checked> Incluir</label><select name="match-${i}"><option value="">Criar item separado</option>${state.items.filter(p=>p.unit===r.unit).map(p=>`<option value="${p.id}" ${p.id===match?.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></td><td><input aria-label="Descrição ${i+1}" name="description-${i}" value="${esc(r.description)}" required></td><td><input aria-label="Embalagem ${i+1}" name="qty-${i}" value="${num(r.qty)}" required inputmode="decimal"></td><td><select name="unit-${i}" aria-label="Unidade ${i+1}">${['g','ml','un'].map(u=>`<option ${r.unit===u?'selected':''}>${u}</option>`).join('')}</select></td><td><input aria-label="Preço sem impostos ${i+1}" name="net-${i}" value="${price(r.net)}" required inputmode="decimal"></td><td><input aria-label="Preço final ${i+1}" name="gross-${i}" value="${price(r.gross)}" required inputmode="decimal"></td><td><input aria-label="Disponível ${i+1}" name="available-${i}" type="checkbox" ${r.available?'checked':''}></td></tr>`}))}<details><summary>Conferir texto completo e linhas não reconhecidas (${draft.unparsed.length})</summary><p>Cabeçalhos, rodapés e itens não reconhecidos estão aqui. Cadastre manualmente qualquer produto faltante.</p><pre>${esc(text)}</pre></details><label class="check"><input type="checkbox" required> Conferi a cotação original, unidades, preços, equivalências e eventuais itens não extraídos.</label><button class="primary" type="submit">Confirmar importação</button></form>`);
}
async function calculate(){if(worker)return;planMode='compare';state=aggregateEquivalentItems(state);persist();view='plan';approved=false;plan=null;worker=new Worker(new URL('./optimizer.worker.js',import.meta.url),{type:'module'});render();worker.onmessage=e=>{worker.terminate();worker=null;if(e.data.error){notice(e.data.error);return}plan=e.data.result;if(plan.status==='feasible'){const best=new Map();for(const item of state.items.filter(i=>i.enabled!==false))for(const c of candidates({...item,lock:'',allowExcess:true},state.offers,state.suppliers)){const key=`${c.itemId}|${c.supplierId}`,old=best.get(key);if(!old||c.gross<old.gross)best.set(key,c)}plan.choices=[...best.values()];plan.selections=lowestSelections(plan.choices);plan.orderSettings=Object.fromEntries(state.suppliers.map(s=>[s.id,{payment:'',freightKnown:s.freightKnown,freightCents:s.freightCents}]));rebuildPlan()}render()};worker.onerror=()=>{worker?.terminate();worker=null;render();notice('Falha no cálculo. Seus dados foram mantidos. Tente novamente.')};worker.postMessage({items:state.items,offers:state.offers,suppliers:state.suppliers})}
async function action(act,id){
 if(act==='tab'){view=id;if(id==='plan')planMode='compare';render()}
 if(act==='plan-mode'){planMode=id;render()}
 if(act==='close')closeImport();
 if(act==='skip-pdf'){pdfIndex++;await nextPDF()}
 if(act==='item')itemForm(id);
 if(act==='offer')offerForm(id);
 if(act==='supplier')supplierForm(id);
 if(act==='buyer')buyerForm();
 if(act==='manual-order-item')manualOrderItemForm(id);
 if(act==='rename')form('Nome da cotação','rename-form',input('title','Nome',state.title,'text','required maxlength="120"'));
 if(act==='remove-item'&&confirm('Excluir este item e todas as ofertas vinculadas? Baixe um backup para manter uma cópia.')){state.items=state.items.filter(i=>i.id!==id);state.offers=state.offers.filter(o=>o.productId!==id);changed()}
 if(act==='remove-offer'&&confirm('Excluir esta oferta?')){state.offers=state.offers.filter(o=>o.id!==id);changed()}
 if(act==='aggregate'){const before=state.items.length;state=aggregateEquivalentItems(state);changed();notice(before===state.items.length?'Nenhum item equivalente novo foi encontrado.':`${before-state.items.length} item(ns) equivalente(s) foram reunidos.`)}
 if(act==='remove-alias'){const removed=state.productAliases.splice(Number(id),1)[0];if(removed?.id)deleteProductAlias(removed.id).then(()=>{globalAliases=globalAliases.filter(a=>a.id!==removed.id)}).catch(err=>notice('Não foi possível remover o aprendizado: '+err.message));changed()}
 if(act==='merge-items'){
  const [targetId,sourceId]=id.split('|'),target=state.items.find(i=>i.id===targetId),source=state.items.find(i=>i.id===sourceId);if(!target||!source)return;
  if(confirm(`Unificar “${source.name}” com “${target.name}”? Esta associação ficará aprendida para as próximas cotações.`)){rememberAlias(source.name,target.name).catch(err=>notice('A unificação foi aplicada, mas não foi guardada globalmente: '+err.message));target.qty=Math.max(target.qty,source.qty);target.allowExcess=Boolean(target.allowExcess||source.allowExcess);for(const o of state.offers)if(o.productId===source.id)o.productId=target.id;state.items=state.items.filter(i=>i.id!==source.id);changed()}
 }
 if(act==='merge-group'){
  const ids=id.split('|'),target=state.items.find(i=>i.id===ids[0]),sources=ids.slice(1).map(sourceId=>state.items.find(i=>i.id===sourceId)).filter(Boolean);if(!target||!sources.length)return;
  if(confirm(`Unificar estes nomes como “${target.name}”? A decisão ficará aprendida para as próximas cotações.`)){for(const source of sources){rememberAlias(source.name,target.name).catch(err=>notice('A unificação foi aplicada, mas não foi guardada globalmente: '+err.message));target.qty=Math.max(target.qty,source.qty);target.enabled=target.enabled!==false||source.enabled!==false;target.allowExcess=Boolean(target.allowExcess||source.allowExcess);if(target.lock!==source.lock)target.lock='';for(const o of state.offers)if(o.productId===source.id)o.productId=target.id}state.items=state.items.filter(i=>!sources.some(source=>source.id===i.id));changed()}
 }
 if(act==='ignore-pair'){const [a,b]=id.split('|').map(x=>state.items.find(i=>i.id===x));if(a&&b){state.ignoredEquivalences??=[];state.ignoredEquivalences.push([normalize(a.name),normalize(b.name)].sort().join('|'));changed()}}
 if(act==='ignore-group'){const grouped=id.split('|').map(itemId=>state.items.find(i=>i.id===itemId)).filter(Boolean);state.ignoredEquivalences??=[];for(let a=0;a<grouped.length;a++)for(let b=a+1;b<grouped.length;b++){const key=[normalize(grouped[a].name),normalize(grouped[b].name)].sort().join('|');if(!state.ignoredEquivalences.includes(key))state.ignoredEquivalences.push(key)}changed()}
 if(act==='new-round')newQuote();
 if(act==='cloud-open'){const row=cloudRounds.find(x=>x.id===id);if(!row)throw Error('Cotação não encontrada.');state=validateState(mergeKnownAliases(structuredClone(row.state)));cloudRoundId=row.id;view='offers';plan=null;approved=false;render()}
 if(act==='cloud-delete'&&confirm('Excluir definitivamente esta cotação da nuvem?')){await deleteCloudRound(id);cloudRounds=cloudRounds.filter(x=>x.id!==id);if(cloudRoundId===id){cloudRoundId=null;state=initial()}render()}
 if(act==='cloud-logout'){await signOut();cloudUser=null;cloudRounds=[];cloudRoundId=null;view='home';render()}
 if(act==='pdf')document.querySelector('#pdf-file').click();
 if(act==='paste')modal('Colar cotação recebida',`<form id="paste-form" class="form-grid">${select('supplierId','Fornecedor', [['','Selecione o fornecedor'],...state.suppliers.map(s=>[s.id,s.name])],'')}<label class="full">Cole os itens usando uma linha para cada embalagem<textarea name="text" required rows="12" placeholder="Produto | Embalagem | Preço sem impostos | Preço final\nÁcido Lático 85% | 1 kg | 34,57 | 34,57\nCondroitina Sulfato de Sódio | 1 kg | 267,40 | 276,13"></textarea></label><div class="full notice"><strong>Exemplo completo:</strong> selecione o fornecedor acima. Depois informe produto, quantidade da embalagem e preços. Se não houver imposto, repita o mesmo valor nas duas últimas colunas.</div><button class="primary full">Interpretar e revisar</button></form>`);
 if(act==='calculate')await calculate();
 if(act==='restore')document.querySelector('#restore-file').click();
 if(act==='backup'){const {download,slug}=await import('./pdf.js');download(JSON.stringify(state,null,2),`${slug(state.title)}.json`,'application/json')}
 if(act==='review-report'){const {download,slug}=await import('./pdf.js');const groups=state.items.map(i=>({produto:i.name,unidade:i.unit,nomesRecebidos:[...new Set(state.offers.filter(o=>o.productId===i.id).map(o=>o.description))],fornecedores:[...new Set(state.offers.filter(o=>o.productId===i.id).map(o=>supplier(o.supplierId)?.name).filter(Boolean))]}));download(JSON.stringify({cotacao:state.title,geradoEm:new Date().toISOString(),base:synonymStats,grupos:groups,equivalenciasAprendidas:state.productAliases,decisoesManterSeparado:state.ignoredEquivalences},null,2),`Mapa-equivalencias-${slug(state.title)}.json`,'application/json')}
 if(['pdf-order','all-pdf','internal-report'].includes(act)){if(plan?.status!=='feasible')throw Error('Calcule os pedidos antes de gerar os arquivos.');if(act!=='internal-report'&&!approved)throw Error('Marque a revisão antes de gerar os pedidos dos fornecedores.');const {download,orderPDF,allPDFs,internalReportPDF,slug}=await import('./pdf.js');if(act==='pdf-order'){const o=plan.orders.find(o=>o.supplier.id===id);download(orderPDF(o,state.buyer,state.title),`Pedido-${slug(o.supplier.name)}.pdf`)}else if(act==='all-pdf')download(allPDFs(plan.orders,state.buyer,state.title),`Pedidos-${slug(state.title)}.zip`,'application/zip');else download(internalReportPDF(plan.orders,{offers:state.offers,items:state.items,suppliers:state.suppliers},state.title),`Relatorio-interno-${slug(state.title)}.pdf`)}
}
root.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b)action(b.dataset.act,b.dataset.id).catch(err=>formError(err.message))});
root.addEventListener('change',async e=>{
 if(e.target.id==='approve'){approved=e.target.checked;render()}
 if(e.target.classList.contains('order-choice')){const item=e.target.dataset.item,offer=e.target.dataset.offer,selected=e.target.checked;if(selected)plan.selections[item]=offer;else if(plan.selections[item]===offer)delete plan.selections[item];approved=false;rebuildPlan();renderInPlace(e.target);notice(selected?'Fornecedor alterado para este produto.':'Produto retirado deste pedido. Você pode marcá-lo em outro fornecedor ou deixá-lo sem compra.');return}
 if(e.target.classList.contains('order-packs')){const c=plan.choices.find(x=>x.offerId===e.target.dataset.offer),packs=Number(e.target.value);if(!c||!Number.isInteger(packs)||packs<=0){notice('Informe um número inteiro de embalagens maior que zero.');renderInPlace(e.target);return}c.packs=packs;c.qty=packs*c.packQty;c.net=packs*c.unitNet;c.gross=packs*c.unitGross;const item=state.items.find(i=>i.id===c.itemId);c.excess=item?Math.max(0,c.qty-item.qty):0;approved=false;rebuildPlan();renderInPlace(e.target);notice('Quantidade e totais atualizados.');return}
 if(e.target.classList.contains('order-payment')){plan.orderSettings[e.target.dataset.id].payment=e.target.value.trim();approved=false;rebuildPlan();renderInPlace(e.target);notice('Condição de pagamento salva neste pedido.');return}
 if(e.target.classList.contains('order-freight')){const raw=e.target.value.trim(),settings=plan.orderSettings[e.target.dataset.id];if(raw===''){settings.freightKnown=false;settings.freightCents=0}else{const value=cents(raw);if(!Number.isSafeInteger(value)||value<0){notice('Frete inválido. Use um valor, 0 para grátis ou deixe vazio para confirmar.');return}settings.freightKnown=true;settings.freightCents=value}approved=false;rebuildPlan();renderInPlace(e.target);notice('Frete atualizado e total recalculado.');return}
 if(e.target.id==='local-save'){local=e.target.checked;try{localStorage.setItem('pharma-local-consent',local?'yes':'no');if(!local)localStorage.removeItem('pharma-round')}catch{}persist();render()}
 if(e.target.id==='considered'){const field=document.querySelector('#exclusion-reason-field'),area=field?.querySelector('textarea');if(field)field.hidden=e.target.checked;if(area){area.required=!e.target.checked;if(e.target.checked)area.value='';else area.focus()}}
 if(e.target.id==='pdf-file'){
  const files=Array.from(e.target.files);e.target.value='';if(!files.length)return;
  pdfQueue=files;pdfIndex=0;await nextPDF();
 }
 if(e.target.id==='restore-file'){
  const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Arquivo maior que 10 MB.');const s=validateState(JSON.parse(await file.text()));if(!hasQuote()||confirm('Abrir esta cotação e substituir a atual? Salve a atual em arquivo antes.')){state={...s,started:true};view='offers';changed()}}catch(err){notice(err.message)}
 }
});
root.addEventListener('submit',e=>{e.preventDefault();const f=e.target;const d=new FormData(f);const get=n=>String(d.get(n)||'');const checked=n=>d.has(n);try{
 if(f.getAttribute('id')==='login-form'){signIn(get('email').trim(),get('password')).then(async user=>{cloudUser=user;await refreshCloudRounds();cloudReady=true;render();if(hasQuote())persist()}).catch(err=>formError(err.message));return}
 if(f.getAttribute('id')==='paste-form'){if(!get('supplierId'))throw Error('Selecione o fornecedor desta cotação.');showDraft(get('text'),get('supplierId'));return}
 if(f.getAttribute('id')==='manual-order-item-form'){
  const supplierId=get('supplierId'),product=get('product').trim(),packs=Number(get('packs')),q=quantity(decimal(get('packQty')),get('unit')),unitNet=cents(get('net')),unitGross=cents(get('gross'));if(!supplier(supplierId)||!product)throw Error('Confira o fornecedor e o produto.');if(!Number.isInteger(packs)||packs<=0)throw Error('O número de embalagens deve ser inteiro e maior que zero.');if(!Number.isSafeInteger(unitNet)||unitNet<=0||!Number.isSafeInteger(unitGross)||unitGross<unitNet)throw Error('Confira os preços: o valor final não pode ser menor que o preço sem impostos.');const net=packs*unitNet,gross=packs*unitGross;if(!Number.isSafeInteger(net)||!Number.isSafeInteger(gross))throw Error('O total informado é muito alto.');const itemId=`manual-${uid()}`,offerId=`manual-${uid()}`;plan.choices.push({itemId,offerId,supplierId,packs,qty:packs*q.qty,unit:q.unit,net,gross,excess:0,pricePerUnit:unitGross/q.qty,product,description:product,reference:get('reference').trim(),packQty:q.qty,unitNet,unitGross,manual:true});plan.selections[itemId]=offerId;approved=false;rebuildPlan();document.querySelector('#modal').close();render();notice(`Item “${product}” incluído no pedido de ${supplier(supplierId).name}.`);return;
 }
 if(f.getAttribute('id')==='new-quote-form'){const title=get('title').trim();if(!title)throw Error('Informe o nome da cotação.');if(hasQuote()&&!checked('replace'))throw Error('Confirme a substituição da cotação atual.');cloudRoundId=null;state=mergeKnownAliases({...state,started:true,title,items:[],offers:[],productAliases:[]});view='offers'}
 if(f.getAttribute('id')==='rename-form')state.title=get('title').trim();
 if(f.getAttribute('id')==='buyer-form')state.buyer=Object.fromEntries(d);
 if(f.getAttribute('id')==='item-form'){
  const q=quantity(decimal(get('qty')),get('unit'));const item={id:get('id')||uid(),name:get('name').trim(),...q,lock:get('lock'),allowExcess:checked('allowExcess'),enabled:checked('enabled')};if(!item.name)throw Error('Informe o produto.');const old=state.items.findIndex(i=>i.id===item.id);if(old>=0)state.items[old]=item;else state.items.push(item);
 }
 if(f.getAttribute('id')==='offer-form'){
  const q=quantity(decimal(get('packQty')),get('unit')),net=cents(get('net')),gross=cents(get('gross'));if(!Number.isSafeInteger(net)||net<=0||!Number.isSafeInteger(gross)||gross<net)throw Error('Confira os preços: o final não pode ser menor que o valor sem impostos.');
  const item=state.items.find(i=>i.id===get('productId'));if(item.unit!==q.unit)throw Error('Unidade incompatível com o produto escolhido.');
  const max=get('maxPacks')===''?null:Number(get('maxPacks'));if(max!==null&&(!Number.isInteger(max)||max<0))throw Error('Máximo disponível deve ser inteiro e não negativo.');
  const considered=checked('considered'),exclusionReason=get('exclusionReason').trim();if(!considered&&exclusionReason.length<10)throw Error('Explique por que esta oferta não deve ser considerada, usando pelo menos 10 caracteres.');
  const o={id:get('id')||uid(),productId:item.id,supplierId:get('supplierId'),description:get('description').trim()||item.name,packQty:q.qty,unit:q.unit,netCents:net,grossCents:gross,maxPacks:max,reference:get('reference'),expires:get('expires'),validity:get('validity'),available:checked('available'),considered,exclusionReason:considered?'':exclusionReason,reviewed:checked('reviewed')};const old=state.offers.findIndex(x=>x.id===o.id);if(old>=0)state.offers[old]=o;else state.offers.push(o);
 }
 if(f.getAttribute('id')==='supplier-form'){
  const min=cents(get('min')),freight=cents(get('freight'));if(!Number.isSafeInteger(min)||min<0||!Number.isSafeInteger(freight)||freight<0)throw Error('Mínimo e frete devem ser valores não negativos.');
  const s={id:get('id')||uid(),name:get('name').trim(),minCents:min,freightCents:freight,freightKnown:checked('freightKnown'),minimumBasis:get('minimumBasis')};if(!s.name)throw Error('Informe o nome.');if(state.suppliers.some(x=>x.id!==s.id&&normalize(x.name)===normalize(s.name)))throw Error('Esse fornecedor já está cadastrado.');const old=state.suppliers.findIndex(x=>x.id===s.id);if(old>=0)state.suppliers[old]=s;else state.suppliers.push(s);
 }
 if(f.getAttribute('id')==='draft-form'){
  if(!get('supplierId'))throw Error('Selecione o fornecedor.');const next=structuredClone(state);let count=0;
  draft.rows.forEach((r,i)=>{if(!checked(`use-${i}`))return;const q=quantity(decimal(get(`qty-${i}`)),get(`unit-${i}`)),net=cents(get(`net-${i}`)),gross=cents(get(`gross-${i}`)),description=get(`description-${i}`).trim();if(!description||!Number.isSafeInteger(net)||net<0||!Number.isSafeInteger(gross)||gross<net)throw Error(`Confira valores da linha ${i+1}.`);if(checked(`available-${i}`)&&net===0)throw Error('Oferta disponível deve ter preço positivo.');let item=next.items.find(x=>x.id===get(`match-${i}`));if(item&&item.unit!==q.unit)throw Error(`Unidade incompatível na linha ${i+1}.`);if(item&&normalize(description)!==normalize(item.name)&&!next.productAliases.some(a=>normalize(a.alias)===normalize(description)&&normalize(a.canonical)===normalize(item.name)))next.productAliases.push({alias:description,canonical:item.name});if(!item){item={id:uid(),name:description,qty:q.qty*Math.max(1,r.quotedPacks||1),unit:q.unit,enabled:true,allowExcess:false,lock:''};next.items.push(item)}
   const o={id:uid(),productId:item.id,supplierId:get('supplierId'),description,packQty:q.qty,unit:q.unit,netCents:net,grossCents:gross,reference:get('reference'),expires:get('expires'),validity:r.validity||'',available:checked(`available-${i}`),considered:true,exclusionReason:'',reviewed:true,maxPacks:null};
   const old=next.offers.findIndex(x=>x.productId===o.productId&&x.supplierId===o.supplierId&&x.packQty===o.packQty&&x.reference===o.reference);if(old>=0)next.offers[old]=o;else next.offers.push(o);count++;
  });if(!count)throw Error('Selecione pelo menos uma linha.');const learned=next.productAliases.filter(a=>!state.productAliases.some(old=>normalize(old.alias)===normalize(a.alias)&&normalize(old.canonical)===normalize(a.canonical)));state=aggregateEquivalentItems(validateState(next));Promise.all(learned.map(a=>rememberAlias(a.alias,a.canonical))).catch(err=>notice('A cotação foi importada, mas um aprendizado não foi salvo: '+err.message));draft=null;
 }
 document.querySelector('#modal').close();changed();
 if(f.getAttribute('id')==='draft-form'&&pdfQueue.length){pdfIndex++;nextPDF().catch(err=>formError(err.message))}
 if(f.getAttribute('id')==='item-form'&&view==='offers')offerForm('');
}catch(err){formError(err.message)}});
window.addEventListener('beforeunload',e=>{if(!local&&!cloudUser&&(state.items.length||state.offers.length)){e.preventDefault();e.returnValue=''}});
root.addEventListener('cancel',e=>{if(e.target.id==='modal'){e.preventDefault();closeImport()}},true);
bootCloud();
