import {jsPDF} from 'jspdf';
import {zipSync} from 'fflate';
import {money} from './core.js';
const clean=s=>String(s??'').replace(/[\u0000-\u001f]/g,' ').replace(/[–—]/g,'-').replace(/[^\u0020-\u00ff]/g,' ');
export const slug=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80);
const quantity=(value,unit)=>`${Number(value||0).toLocaleString('pt-BR',{maximumFractionDigits:3})} ${unit||''}`.trim();
const requestedQuantity=(value,unit)=>{const n=Number(value||0);if(unit==='g'&&n>=1000&&n%1000===0)return quantity(n/1000,'kg');if(unit==='ml'&&n>=1000&&n%1000===0)return quantity(n/1000,'L');return quantity(n,unit)};
export function quotationRequestPDF(items,buyer,round,settings={},date=new Date()){
 if(!items?.length)throw Error('Adicione pelo menos um produto à solicitação.');const doc=new jsPDF();let y=20;const text=(s,x,yy,opt)=>doc.text(clean(s),x,yy,opt);
 function header(){doc.setFillColor(49,85,31);doc.rect(0,0,210,37,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(17);text('SOLICITAÇÃO DE COTAÇÃO',15,17);doc.setFontSize(9);text('PHARMAPENHA',15,25);doc.setFont('helvetica','normal');text(`${round} | ${date.toLocaleDateString('pt-BR')}`,195,25,{align:'right'});doc.setTextColor(33,48,36);y=47}
 function page(){doc.addPage();header();tableHeader()}
 function tableHeader(){doc.setFillColor(49,85,31);doc.roundedRect(15,y-4,180,10,2,2,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(8);text('ITEM',20,y+2);text('PRODUTO / ESPECIFICAÇÃO',32,y+2);text('QUANTIDADE SOLICITADA',190,y+2,{align:'right'});doc.setTextColor(33,48,36);y+=12}
 header();doc.setFillColor(238,247,232);doc.roundedRect(15,y-5,180,25,3,3,'F');doc.setTextColor(94,113,87);doc.setFont('helvetica','normal');doc.setFontSize(8);text('SOLICITANTE',20,y+1);doc.setTextColor(49,85,31);doc.setFont('helvetica','bold');doc.setFontSize(12);text(buyer?.name||'Pharmapenha',20,y+9);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(33,48,36);const details=[buyer?.cnpj&&`CNPJ: ${buyer.cnpj}`,buyer?.contact&&`Contato: ${buyer.contact}`].filter(Boolean).join('   |   ');if(details)text(details,20,y+17);y+=34;
 doc.setFont('helvetica','normal');doc.setFontSize(9);text('Solicitamos sua melhor cotação para os itens abaixo.',15,y);if(settings.deadline){doc.setFont('helvetica','bold');text(`Responder até: ${new Date(settings.deadline+'T12:00:00').toLocaleDateString('pt-BR')}`,195,y,{align:'right'})}y+=11;tableHeader();
 items.forEach((item,index)=>{const lines=doc.splitTextToSize(clean(item.name),125),height=Math.max(13,lines.length*5+5);if(y+height>266)page();doc.setFont('helvetica','bold');doc.setFontSize(9);text(String(index+1).padStart(2,'0'),20,y);lines.forEach((line,i)=>text(line,32,y+i*5));doc.setFont('helvetica','normal');text(requestedQuantity(item.qty,item.unit),190,y,{align:'right'});y+=height;doc.setDrawColor(226,232,223);doc.line(15,y-3,195,y-3)});
 const instructions=['Informar quantidade da embalagem ou fracionamento','Preço da embalagem sem impostos e preço final com impostos','Disponibilidade, validade e prazo de entrega','Condição de pagamento, frete e pedido mínimo'];const noteLines=settings.notes?doc.splitTextToSize(clean(`Observações: ${settings.notes}`),168):[],boxHeight=29+noteLines.length*4.5;if(y+boxHeight>271){doc.addPage();header()}y+=6;doc.setFillColor(248,250,247);doc.roundedRect(15,y-4,180,boxHeight,3,3,'F');doc.setTextColor(49,85,31);doc.setFont('helvetica','bold');doc.setFontSize(9);text('INFORMAÇÕES NECESSÁRIAS NA RESPOSTA',20,y+3);doc.setTextColor(33,48,36);doc.setFont('helvetica','normal');doc.setFontSize(8);instructions.forEach((line,i)=>text(`- ${line}`,20,y+10+i*5));if(noteLines.length){doc.setFont('helvetica','bold');noteLines.forEach((line,i)=>text(line,20,y+31+i*4.5))}
 const n=doc.getNumberOfPages();for(let i=1;i<=n;i++){doc.setPage(i);doc.setFontSize(8);doc.setTextColor(90);text('Este mesmo documento foi enviado aos fornecedores participantes.',15,286);text(`Página ${i} de ${n}`,195,286,{align:'right'})}return new Uint8Array(doc.output('arraybuffer'))
}
export function orderPDF(order,buyer,round,date=new Date()){
 if(!order.valid)throw Error('Pedido abaixo do mínimo. PDF bloqueado.');
 const doc=new jsPDF();let y=20;
 const freightKnown=order.freightKnown??order.supplier.freightKnown,freightCents=order.freightCents??order.supplier.freightCents;
 const text=(s,x,yy,opt)=>doc.text(clean(s),x,yy,opt);
 function header(){doc.setFillColor(49,85,31);doc.rect(0,0,210,37,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(17);text('PEDIDO DE COMPRA',15,17);doc.setFontSize(9);text('PHARMAPENHA',15,25);doc.setFont('helvetica','normal');text(`${round} | ${date.toLocaleDateString('pt-BR')}`,195,25,{align:'right'});doc.setTextColor(33,48,36);y=47}
 function page(){doc.addPage();header()}
 function ensure(h=12){if(y+h>276)page()}
 function para(s,bold=false,x=15,width=179){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(9);for(const line of doc.splitTextToSize(clean(s),width)){ensure(5);text(line,x,y);y+=5}}
 header();doc.setFillColor(238,247,232);doc.roundedRect(15,y-5,180,18,3,3,'F');doc.setTextColor(94,113,87);doc.setFont('helvetica','normal');doc.setFontSize(8);text('FORNECEDOR',20,y+1);doc.setTextColor(49,85,31);doc.setFont('helvetica','bold');doc.setFontSize(14);text(order.supplier.name,20,y+9);doc.setTextColor(33,48,36);y+=23;
 doc.setFillColor(248,250,247);doc.roundedRect(15,y,180,28,3,3,'F');doc.setFontSize(8);doc.setTextColor(106,120,108);text('COMPRADOR / EMPRESA',20,y+7);doc.setTextColor(33,48,36);doc.setFont('helvetica','bold');doc.setFontSize(10);text(buyer.name||'Pharmapenha',20,y+14);doc.setFont('helvetica','normal');doc.setFontSize(8);if(buyer.cnpj)text(`CNPJ: ${buyer.cnpj}`,20,y+21);if(buyer.contact)text(`Contato: ${buyer.contact}`,105,y+14);if(buyer.address){const address=doc.splitTextToSize(clean(`Entrega: ${buyer.address}`),85);address.slice(0,2).forEach((line,i)=>text(line,105,y+21+i*4))}y+=35;
 doc.setFillColor(248,250,247);doc.roundedRect(15,y,87,20,3,3,'F');doc.roundedRect(108,y,87,20,3,3,'F');doc.setTextColor(106,120,108);doc.setFontSize(8);text('CONDIÇÃO DE PAGAMENTO',20,y+7);text('FRETE',113,y+7);doc.setTextColor(33,48,36);doc.setFont('helvetica','bold');doc.setFontSize(10);text(order.payment||'A combinar',20,y+15);text(freightKnown?money(freightCents):'A confirmar',113,y+15);y+=29;
 function tableHeader(){doc.setFillColor(49,85,31);doc.roundedRect(15,y-4,180,10,2,2,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(8);text('PRODUTO / REFERÊNCIA',19,y+2);text('QUANTIDADE TOTAL',139,y+2,{align:'right'});text('PREÇO EMB.',169,y+2,{align:'right'});text('TOTAL',191,y+2,{align:'right'});doc.setTextColor(33,48,36);doc.setFont('helvetica','normal');y+=12}
 tableHeader();
 for(const line of order.lines){
  const description=doc.splitTextToSize(clean(line.description),87);
  const refs=line.reference?doc.splitTextToSize(`Ref. cotação: ${clean(line.reference)}`,87):[];
  const height=Math.max(16,(description.length+refs.length)*4.5+5);
  if(y+height>267){page();tableHeader()}
  doc.setFontSize(9);doc.setFont('helvetica','bold');description.forEach((s,i)=>text(s,19,y+i*4.5));doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(106,120,108);refs.forEach((s,i)=>text(s,19,y+(description.length+i)*4.5));doc.setTextColor(33,48,36);doc.setFontSize(8.5);
  const totalQty=Number(line.packs||0)*Number(line.packQty||0);text(quantity(totalQty,line.unit),139,y,{align:'right'});text(money(line.unitGross),169,y,{align:'right'});doc.setFont('helvetica','bold');text(money(line.gross),191,y,{align:'right'});
  y+=height;doc.setDrawColor(226,232,223);doc.line(15,y-3,195,y-3);
 }
 if(y>220)page();y+=4;doc.setFillColor(248,250,247);doc.roundedRect(105,y,90,39,3,3,'F');doc.setFontSize(8);doc.setFont('helvetica','normal');text('Produtos sem impostos',110,y+8);text(money(order.net),190,y+8,{align:'right'});text('Impostos informados',110,y+15);text(money(order.tax),190,y+15,{align:'right'});text('Produtos com impostos',110,y+22);text(money(order.gross),190,y+22,{align:'right'});text('Frete',110,y+29);text(freightKnown?money(freightCents):'A confirmar',190,y+29,{align:'right'});doc.setFillColor(76,151,63);doc.roundedRect(105,y+32,90,15,3,3,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(11);text(freightKnown?'TOTAL DO PEDIDO':'TOTAL ESTIMADO',110,y+42);text(money(order.total),190,y+42,{align:'right'});doc.setTextColor(33,48,36);y+=54;
 const notices=[];if(buyer.notes)notices.push(`Observações: ${buyer.notes}`);notices.push('Favor confirmar disponibilidade, validade, condições de pagamento e prazo de entrega.');const noticeLines=notices.flatMap(note=>doc.splitTextToSize(clean(note),168)),noticeHeight=noticeLines.length*5+8;ensure(noticeHeight);doc.setFillColor(buyer.notes?255:238,buyer.notes?249:247,buyer.notes?232:232);doc.roundedRect(15,y-4,180,noticeHeight,3,3,'F');doc.setFont('helvetica','bold');doc.setFontSize(8.5);noticeLines.forEach((line,i)=>text(line,20,y+2+i*5));y+=noticeHeight+3;
 const n=doc.getNumberOfPages();for(let i=1;i<=n;i++){doc.setPage(i);doc.setFontSize(8);text(`Página ${i} de ${n}`,195,286,{align:'right'})}
 return new Uint8Array(doc.output('arraybuffer'));
}
export function download(bytes,name,type='application/pdf'){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
export function allPDFs(orders,buyer,round){const files={};orders.forEach((o,i)=>{files[`${i+1}-Pedido-${slug(o.supplier.name)}.pdf`]=orderPDF(o,buyer,round)});return zipSync(files)}
export function internalReportPDF(orders,audit,round,date=new Date()){
 const doc=new jsPDF();let y=20;const text=(s,x,yy,opt)=>doc.text(clean(s),x,yy,opt);
 function header(){doc.setFillColor(49,85,31);doc.rect(0,0,210,37,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(17);text('RELATÓRIO INTERNO DA COMPRA',15,17);doc.setFontSize(9);text('USO INTERNO - PHARMAPENHA',15,25);doc.setFont('helvetica','normal');text(`${round} | ${date.toLocaleDateString('pt-BR')}`,195,25,{align:'right'});doc.setTextColor(33,48,36);y=47}
 function page(){doc.addPage();header()}
 function ensure(h=12){if(y+h>276)page()}
 function para(s,bold=false,x=15,width=179){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(9);for(const line of doc.splitTextToSize(clean(s),width)){ensure(5);text(line,x,y);y+=5}}
 function sectionTitle(title,subtitle=''){ensure(subtitle?22:15);y+=4;doc.setFillColor(238,247,232);doc.roundedRect(15,y-5,180,subtitle?18:11,2,2,'F');doc.setTextColor(49,85,31);doc.setFont('helvetica','bold');doc.setFontSize(11);text(title,20,y+2);if(subtitle){doc.setTextColor(94,113,87);doc.setFont('helvetica','normal');doc.setFontSize(8);text(subtitle,20,y+8)}doc.setTextColor(33,48,36);y+=subtitle?22:15}
 header();para('Documento consolidado para conferência dos pedidos e das notas fiscais. Não enviar aos fornecedores.');y+=3;
 const grandTotal=orders.reduce((t,o)=>t+o.total,0);doc.setFillColor(248,250,247);doc.roundedRect(15,y,87,22,3,3,'F');doc.roundedRect(108,y,87,22,3,3,'F');doc.setFontSize(8);doc.setTextColor(106,120,108);text('Total geral previsto',20,y+7);text('Fornecedores com pedido',113,y+7);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.setTextColor(49,85,31);text(money(grandTotal),20,y+16);text(String(orders.length),113,y+16);doc.setTextColor(33,48,36);y+=29;
 sectionTitle('PEDIDOS QUE SERÃO REALIZADOS','Separados por fornecedor para conferência com as notas fiscais.');
 for(const order of orders){ensure(30);doc.setFillColor(49,85,31);doc.roundedRect(15,y,180,13,2,2,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(11);text(order.supplier.name,20,y+8);text(money(order.total),190,y+8,{align:'right'});doc.setTextColor(33,48,36);y+=18;para(`Pagamento: ${order.payment||'a combinar'}   |   Frete: ${order.freightKnown?money(order.freightCents):'a confirmar'}`,false,20,170);y+=2;
  doc.setFillColor(244,247,243);doc.rect(20,y-4,170,8,'F');doc.setFont('helvetica','bold');doc.setFontSize(8);text('PRODUTO',23,y+1);text('EMBALAGENS',137,y+1,{align:'right'});text('TOTAL',187,y+1,{align:'right'});y+=9;
  for(const line of order.lines){ensure(12);const name=doc.splitTextToSize(clean(line.product||line.description),98),height=Math.max(10,name.length*4+3);name.forEach((v,i)=>text(v,23,y+i*4));doc.setFont('helvetica','normal');text(`${line.packs} x ${line.packQty} ${line.unit}`,137,y,{align:'right'});doc.setFont('helvetica','bold');text(money(line.gross),187,y,{align:'right'});y+=height;doc.setDrawColor(226,232,223);doc.line(20,y-3,190,y-3)}
  y+=2;doc.setFont('helvetica','bold');para(`Produtos: ${money(order.gross)}   |   Total do pedido: ${money(order.total)}`,true,20,170);y+=8;
 }
 if(!orders.length)para('Nenhum pedido foi selecionado.',true);
 const chosen=new Map();for(const order of orders)for(const line of order.lines)chosen.set(line.itemId,{line,supplier:order.supplier});
 const unselected=(audit.items||[]).filter(i=>i.enabled!==false&&!chosen.has(i.id));if(unselected.length){sectionTitle('PRODUTOS SEM COMPRA');for(const item of unselected)para(`${item.name} - necessidade: ${item.qty} ${item.unit}`,true,20,170);y+=4}
 const excluded=(audit.offers||[]).filter(o=>o.considered===false&&chosen.has(o.productId));if(excluded.length){sectionTitle('JUSTIFICATIVAS REGISTRADAS','Ofertas retiradas da comparação pelo comprador.');for(const o of excluded){const picked=chosen.get(o.productId),item=(audit.items||[]).find(i=>i.id===o.productId),supplier=(audit.suppliers||[]).find(s=>s.id===o.supplierId);ensure(25);doc.setFillColor(255,249,232);doc.roundedRect(20,y-3,170,20,2,2,'F');para(item?.name||picked.line.product||o.description,true,24,162);para(`${supplier?.name||'Fornecedor'} - ${money(o.grossCents)} por ${o.packQty} ${o.unit}`,false,24,162);para(`Motivo: ${o.exclusionReason}`,true,24,162);y+=5}}
 sectionTitle('COMPARATIVO COMPLETO','Verde = menor desembolso. "Escolhida" = opção incluída no pedido.');
 const choices=audit.choices||[],selections=audit.selections||{},reasons=audit.choiceReasons||{};
 for(const item of (audit.items||[]).filter(i=>i.enabled!==false)){const options=choices.filter(c=>c.itemId===item.id).sort((a,b)=>a.gross-b.gross);if(!options.length)continue;ensure(18+options.length*13+(validReasonText(reasons[item.id])?14:0));doc.setFillColor(246,248,245);doc.roundedRect(15,y-4,180,11,2,2,'F');doc.setFont('helvetica','bold');doc.setFontSize(10);text(item.name,20,y+2);doc.setFontSize(8);text(`Necessidade: ${item.qty} ${item.unit}`,190,y+2,{align:'right'});y+=14;const cheapest=Math.min(...options.map(c=>c.gross));
  for(const c of options){const s=(audit.suppliers||[]).find(x=>x.id===c.supplierId),isCheapest=c.gross===cheapest,isChosen=selections[item.id]===c.offerId,label=`${s?.name||'Fornecedor'}  |  ${c.packs} x ${c.packQty} ${c.unit}  |  ${money(c.gross)}`,tags=`${isCheapest?'MENOR DESEMBOLSO':''}${isCheapest&&isChosen?' + ':''}${isChosen?'ESCOLHIDA':''}`;ensure(13);if(isCheapest){doc.setFillColor(242,249,238);doc.setDrawColor(76,151,63);doc.roundedRect(20,y-4,170,11,2,2,'FD')}doc.setFont('helvetica',isChosen?'bold':'normal');doc.setFontSize(8.5);text(label,24,y+2);if(tags){doc.setTextColor(isCheapest?55:49,115,45);doc.setFont('helvetica','bold');doc.setFontSize(7);text(tags,187,y+2,{align:'right'});doc.setTextColor(33,48,36)}y+=13}
  const optionIds=new Set(options.map(c=>c.offerId));for(const o of (audit.offers||[]).filter(o=>o.productId===item.id&&!optionIds.has(o.id))){const s=(audit.suppliers||[]).find(x=>x.id===o.supplierId),status=o.considered===false?'desconsiderada':o.available===false?'indisponível':'não comparável';para(`${s?.name||'Fornecedor'} | ${money(o.grossCents)} por ${o.packQty} ${o.unit} | ${status}`,false,24,162)}
  const chosenOption=options.find(c=>selections[item.id]===c.offerId);if(chosenOption&&chosenOption.gross>cheapest&&validReasonText(reasons[item.id])){ensure(14);doc.setFillColor(255,247,222);doc.roundedRect(20,y-3,170,11,2,2,'F');para(`Motivo da escolha: ${reasons[item.id]}`,true,24,162);y+=3}y+=5}
 const manual=orders.flatMap(o=>o.lines.map(line=>({line,supplier:o.supplier}))).filter(x=>x.line.manual);if(manual.length){sectionTitle('ITENS INCLUÍDOS MANUALMENTE');for(const {line,supplier} of manual){ensure(20);para(`${line.product||line.description} | ${supplier.name} | ${money(line.gross)}`,true,20,170);para(`Motivo: ${line.decisionReason||'Não informado'}`,false,20,170);y+=5}}
 const n=doc.getNumberOfPages();for(let i=1;i<=n;i++){doc.setPage(i);doc.setFontSize(8);text(`Página ${i} de ${n}`,195,286,{align:'right'})}
 return new Uint8Array(doc.output('arraybuffer'));
}
function validReasonText(value){return String(value||'').trim().length>=10}
